// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: smm/v1/delete_course_rpc.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "smm.v1";

export interface DeleteCourseRequest {
  dataId: bigint;
}

export interface DeleteCourseResponse {
  success: boolean;
  courseName: string;
}

function createBaseDeleteCourseRequest(): DeleteCourseRequest {
  return { dataId: 0n };
}

export const DeleteCourseRequest: MessageFns<DeleteCourseRequest> = {
  encode(message: DeleteCourseRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.dataId !== 0n) {
      if (BigInt.asUintN(64, message.dataId) !== message.dataId) {
        throw new globalThis.Error("value provided for field message.dataId of type uint64 too large");
      }
      writer.uint32(8).uint64(message.dataId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteCourseRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteCourseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.dataId = reader.uint64() as bigint;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteCourseRequest {
    return { dataId: isSet(object.dataId) ? BigInt(object.dataId) : 0n };
  },

  toJSON(message: DeleteCourseRequest): unknown {
    const obj: any = {};
    if (message.dataId !== 0n) {
      obj.dataId = message.dataId.toString();
    }
    return obj;
  },

  create(base?: DeepPartial<DeleteCourseRequest>): DeleteCourseRequest {
    return DeleteCourseRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeleteCourseRequest>): DeleteCourseRequest {
    const message = createBaseDeleteCourseRequest();
    message.dataId = object.dataId ?? 0n;
    return message;
  },
};

function createBaseDeleteCourseResponse(): DeleteCourseResponse {
  return { success: false, courseName: "" };
}

export const DeleteCourseResponse: MessageFns<DeleteCourseResponse> = {
  encode(message: DeleteCourseResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.courseName !== "") {
      writer.uint32(18).string(message.courseName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteCourseResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteCourseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.courseName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteCourseResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      courseName: isSet(object.courseName) ? globalThis.String(object.courseName) : "",
    };
  },

  toJSON(message: DeleteCourseResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.courseName !== "") {
      obj.courseName = message.courseName;
    }
    return obj;
  },

  create(base?: DeepPartial<DeleteCourseResponse>): DeleteCourseResponse {
    return DeleteCourseResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeleteCourseResponse>): DeleteCourseResponse {
    const message = createBaseDeleteCourseResponse();
    message.success = object.success ?? false;
    message.courseName = object.courseName ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
