/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter eslint_disable,output_javascript,output_legacy_commonjs,ts_nocheck
// @generated from protobuf file "api/v2/api_service.proto" (package "api.v2", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import type { SetStripeConnectionDataResponse } from "./set_stripe_connection_data_rpc";
import type { SetStripeConnectionDataRequest } from "./set_stripe_connection_data_rpc";
import type { SetDiscordConnectionDataResponse } from "./set_discord_connection_data_rpc";
import type { SetDiscordConnectionDataRequest } from "./set_discord_connection_data_rpc";
import type { ResetPasswordResponse } from "./reset_password_rpc";
import type { ResetPasswordRequest } from "./reset_password_rpc";
import type { ForgotPasswordResponse } from "./forgot_password_rpc";
import type { ForgotPasswordRequest } from "./forgot_password_rpc";
import type { UpdateUserDataResponse } from "./update_user_data_rpc";
import type { UpdateUserDataRequest } from "./update_user_data_rpc";
import type { GetUserDataResponse } from "./get_user_data_rpc";
import type { GetUserDataRequest } from "./get_user_data_rpc";
import type { LoginResponse } from "./login_rpc";
import type { LoginRequest } from "./login_rpc";
import type { RegisterResponse } from "./register_rpc";
import type { RegisterRequest } from "./register_rpc";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service api.v2.ApiService
 */
export interface IApiServiceClient {
    /**
     * @generated from protobuf rpc: Register(api.v2.RegisterRequest) returns (api.v2.RegisterResponse);
     */
    register(input: RegisterRequest, options?: RpcOptions): UnaryCall<RegisterRequest, RegisterResponse>;
    /**
     * @generated from protobuf rpc: Login(api.v2.LoginRequest) returns (api.v2.LoginResponse);
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResponse>;
    /**
     * @generated from protobuf rpc: GetUserData(api.v2.GetUserDataRequest) returns (api.v2.GetUserDataResponse);
     */
    getUserData(input: GetUserDataRequest, options?: RpcOptions): UnaryCall<GetUserDataRequest, GetUserDataResponse>;
    /**
     * @generated from protobuf rpc: UpdateUserData(api.v2.UpdateUserDataRequest) returns (api.v2.UpdateUserDataResponse);
     */
    updateUserData(input: UpdateUserDataRequest, options?: RpcOptions): UnaryCall<UpdateUserDataRequest, UpdateUserDataResponse>;
    /**
     * @generated from protobuf rpc: ForgotPassword(api.v2.ForgotPasswordRequest) returns (api.v2.ForgotPasswordResponse);
     */
    forgotPassword(input: ForgotPasswordRequest, options?: RpcOptions): UnaryCall<ForgotPasswordRequest, ForgotPasswordResponse>;
    /**
     * @generated from protobuf rpc: ResetPassword(api.v2.ResetPasswordRequest) returns (api.v2.ResetPasswordResponse);
     */
    resetPassword(input: ResetPasswordRequest, options?: RpcOptions): UnaryCall<ResetPasswordRequest, ResetPasswordResponse>;
    /**
     * @generated from protobuf rpc: SetDiscordConnectionData(api.v2.SetDiscordConnectionDataRequest) returns (api.v2.SetDiscordConnectionDataResponse);
     */
    setDiscordConnectionData(input: SetDiscordConnectionDataRequest, options?: RpcOptions): UnaryCall<SetDiscordConnectionDataRequest, SetDiscordConnectionDataResponse>;
    /**
     * @generated from protobuf rpc: SetStripeConnectionData(api.v2.SetStripeConnectionDataRequest) returns (api.v2.SetStripeConnectionDataResponse);
     */
    setStripeConnectionData(input: SetStripeConnectionDataRequest, options?: RpcOptions): UnaryCall<SetStripeConnectionDataRequest, SetStripeConnectionDataResponse>;
}
/**
 * @generated from protobuf service api.v2.ApiService
 */
export declare class ApiServiceClient implements IApiServiceClient, ServiceInfo {
    private readonly _transport;
    typeName: any;
    methods: any;
    options: any;
    constructor(_transport: RpcTransport);
    /**
     * @generated from protobuf rpc: Register(api.v2.RegisterRequest) returns (api.v2.RegisterResponse);
     */
    register(input: RegisterRequest, options?: RpcOptions): UnaryCall<RegisterRequest, RegisterResponse>;
    /**
     * @generated from protobuf rpc: Login(api.v2.LoginRequest) returns (api.v2.LoginResponse);
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResponse>;
    /**
     * @generated from protobuf rpc: GetUserData(api.v2.GetUserDataRequest) returns (api.v2.GetUserDataResponse);
     */
    getUserData(input: GetUserDataRequest, options?: RpcOptions): UnaryCall<GetUserDataRequest, GetUserDataResponse>;
    /**
     * @generated from protobuf rpc: UpdateUserData(api.v2.UpdateUserDataRequest) returns (api.v2.UpdateUserDataResponse);
     */
    updateUserData(input: UpdateUserDataRequest, options?: RpcOptions): UnaryCall<UpdateUserDataRequest, UpdateUserDataResponse>;
    /**
     * @generated from protobuf rpc: ForgotPassword(api.v2.ForgotPasswordRequest) returns (api.v2.ForgotPasswordResponse);
     */
    forgotPassword(input: ForgotPasswordRequest, options?: RpcOptions): UnaryCall<ForgotPasswordRequest, ForgotPasswordResponse>;
    /**
     * @generated from protobuf rpc: ResetPassword(api.v2.ResetPasswordRequest) returns (api.v2.ResetPasswordResponse);
     */
    resetPassword(input: ResetPasswordRequest, options?: RpcOptions): UnaryCall<ResetPasswordRequest, ResetPasswordResponse>;
    /**
     * @generated from protobuf rpc: SetDiscordConnectionData(api.v2.SetDiscordConnectionDataRequest) returns (api.v2.SetDiscordConnectionDataResponse);
     */
    setDiscordConnectionData(input: SetDiscordConnectionDataRequest, options?: RpcOptions): UnaryCall<SetDiscordConnectionDataRequest, SetDiscordConnectionDataResponse>;
    /**
     * @generated from protobuf rpc: SetStripeConnectionData(api.v2.SetStripeConnectionDataRequest) returns (api.v2.SetStripeConnectionDataResponse);
     */
    setStripeConnectionData(input: SetStripeConnectionDataRequest, options?: RpcOptions): UnaryCall<SetStripeConnectionDataRequest, SetStripeConnectionDataResponse>;
}
