"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: miiverse/v2/post.proto
Object.defineProperty(exports, "__esModule", { value: true });
exports.PostData = exports.PostBinaryData = exports.PostTopicTag = exports.PostScreenshot = exports.PostPainting = exports.LanguageID = exports.FeelingID = exports.SortBy = exports.QueryType = exports.PostType = exports.protobufPackage = void 0;
exports.postTypeFromJSON = postTypeFromJSON;
exports.postTypeToJSON = postTypeToJSON;
exports.queryTypeFromJSON = queryTypeFromJSON;
exports.queryTypeToJSON = queryTypeToJSON;
exports.sortByFromJSON = sortByFromJSON;
exports.sortByToJSON = sortByToJSON;
exports.feelingIDFromJSON = feelingIDFromJSON;
exports.feelingIDToJSON = feelingIDToJSON;
exports.languageIDFromJSON = languageIDFromJSON;
exports.languageIDToJSON = languageIDToJSON;
/* eslint-disable */
const wire_1 = require("@bufbuild/protobuf/wire");
exports.protobufPackage = "miiverse.v2";
var PostType;
(function (PostType) {
    PostType[PostType["POST_TYPE_ANY_UNSPECIFIED"] = 0] = "POST_TYPE_ANY_UNSPECIFIED";
    PostType[PostType["POST_TYPE_TEXT"] = 1] = "POST_TYPE_TEXT";
    PostType[PostType["POST_TYPE_MEMO"] = 2] = "POST_TYPE_MEMO";
    PostType[PostType["POST_TYPE_SCREENSHOT"] = 3] = "POST_TYPE_SCREENSHOT";
    PostType[PostType["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(PostType || (exports.PostType = PostType = {}));
function postTypeFromJSON(object) {
    switch (object) {
        case 0:
        case "POST_TYPE_ANY_UNSPECIFIED":
            return PostType.POST_TYPE_ANY_UNSPECIFIED;
        case 1:
        case "POST_TYPE_TEXT":
            return PostType.POST_TYPE_TEXT;
        case 2:
        case "POST_TYPE_MEMO":
            return PostType.POST_TYPE_MEMO;
        case 3:
        case "POST_TYPE_SCREENSHOT":
            return PostType.POST_TYPE_SCREENSHOT;
        case -1:
        case "UNRECOGNIZED":
        default:
            return PostType.UNRECOGNIZED;
    }
}
function postTypeToJSON(object) {
    switch (object) {
        case PostType.POST_TYPE_ANY_UNSPECIFIED:
            return "POST_TYPE_ANY_UNSPECIFIED";
        case PostType.POST_TYPE_TEXT:
            return "POST_TYPE_TEXT";
        case PostType.POST_TYPE_MEMO:
            return "POST_TYPE_MEMO";
        case PostType.POST_TYPE_SCREENSHOT:
            return "POST_TYPE_SCREENSHOT";
        case PostType.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
var QueryType;
(function (QueryType) {
    QueryType[QueryType["QUERY_TYPE_UNSPECIFIED"] = 0] = "QUERY_TYPE_UNSPECIFIED";
    QueryType[QueryType["QUERY_TYPE_FOLLOWINGS"] = 1] = "QUERY_TYPE_FOLLOWINGS";
    QueryType[QueryType["QUERY_TYPE_SELF"] = 2] = "QUERY_TYPE_SELF";
    QueryType[QueryType["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(QueryType || (exports.QueryType = QueryType = {}));
function queryTypeFromJSON(object) {
    switch (object) {
        case 0:
        case "QUERY_TYPE_UNSPECIFIED":
            return QueryType.QUERY_TYPE_UNSPECIFIED;
        case 1:
        case "QUERY_TYPE_FOLLOWINGS":
            return QueryType.QUERY_TYPE_FOLLOWINGS;
        case 2:
        case "QUERY_TYPE_SELF":
            return QueryType.QUERY_TYPE_SELF;
        case -1:
        case "UNRECOGNIZED":
        default:
            return QueryType.UNRECOGNIZED;
    }
}
function queryTypeToJSON(object) {
    switch (object) {
        case QueryType.QUERY_TYPE_UNSPECIFIED:
            return "QUERY_TYPE_UNSPECIFIED";
        case QueryType.QUERY_TYPE_FOLLOWINGS:
            return "QUERY_TYPE_FOLLOWINGS";
        case QueryType.QUERY_TYPE_SELF:
            return "QUERY_TYPE_SELF";
        case QueryType.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
var SortBy;
(function (SortBy) {
    SortBy[SortBy["SORT_BY_UNSPECIFIED"] = 0] = "SORT_BY_UNSPECIFIED";
    SortBy[SortBy["SORT_BY_NEW"] = 1] = "SORT_BY_NEW";
    SortBy[SortBy["SORT_BY_POPULAR"] = 2] = "SORT_BY_POPULAR";
    SortBy[SortBy["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(SortBy || (exports.SortBy = SortBy = {}));
function sortByFromJSON(object) {
    switch (object) {
        case 0:
        case "SORT_BY_UNSPECIFIED":
            return SortBy.SORT_BY_UNSPECIFIED;
        case 1:
        case "SORT_BY_NEW":
            return SortBy.SORT_BY_NEW;
        case 2:
        case "SORT_BY_POPULAR":
            return SortBy.SORT_BY_POPULAR;
        case -1:
        case "UNRECOGNIZED":
        default:
            return SortBy.UNRECOGNIZED;
    }
}
function sortByToJSON(object) {
    switch (object) {
        case SortBy.SORT_BY_UNSPECIFIED:
            return "SORT_BY_UNSPECIFIED";
        case SortBy.SORT_BY_NEW:
            return "SORT_BY_NEW";
        case SortBy.SORT_BY_POPULAR:
            return "SORT_BY_POPULAR";
        case SortBy.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
var FeelingID;
(function (FeelingID) {
    FeelingID[FeelingID["FEELING_ID_NORMAL_UNSPECIFIED"] = 0] = "FEELING_ID_NORMAL_UNSPECIFIED";
    FeelingID[FeelingID["FEELING_ID_HAPPY"] = 1] = "FEELING_ID_HAPPY";
    FeelingID[FeelingID["FEELING_ID_LIKE"] = 2] = "FEELING_ID_LIKE";
    FeelingID[FeelingID["FEELING_ID_SURPRISED"] = 3] = "FEELING_ID_SURPRISED";
    FeelingID[FeelingID["FEELING_ID_FRUSTRATED"] = 4] = "FEELING_ID_FRUSTRATED";
    FeelingID[FeelingID["FEELING_ID_PUZZLED"] = 5] = "FEELING_ID_PUZZLED";
    FeelingID[FeelingID["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(FeelingID || (exports.FeelingID = FeelingID = {}));
function feelingIDFromJSON(object) {
    switch (object) {
        case 0:
        case "FEELING_ID_NORMAL_UNSPECIFIED":
            return FeelingID.FEELING_ID_NORMAL_UNSPECIFIED;
        case 1:
        case "FEELING_ID_HAPPY":
            return FeelingID.FEELING_ID_HAPPY;
        case 2:
        case "FEELING_ID_LIKE":
            return FeelingID.FEELING_ID_LIKE;
        case 3:
        case "FEELING_ID_SURPRISED":
            return FeelingID.FEELING_ID_SURPRISED;
        case 4:
        case "FEELING_ID_FRUSTRATED":
            return FeelingID.FEELING_ID_FRUSTRATED;
        case 5:
        case "FEELING_ID_PUZZLED":
            return FeelingID.FEELING_ID_PUZZLED;
        case -1:
        case "UNRECOGNIZED":
        default:
            return FeelingID.UNRECOGNIZED;
    }
}
function feelingIDToJSON(object) {
    switch (object) {
        case FeelingID.FEELING_ID_NORMAL_UNSPECIFIED:
            return "FEELING_ID_NORMAL_UNSPECIFIED";
        case FeelingID.FEELING_ID_HAPPY:
            return "FEELING_ID_HAPPY";
        case FeelingID.FEELING_ID_LIKE:
            return "FEELING_ID_LIKE";
        case FeelingID.FEELING_ID_SURPRISED:
            return "FEELING_ID_SURPRISED";
        case FeelingID.FEELING_ID_FRUSTRATED:
            return "FEELING_ID_FRUSTRATED";
        case FeelingID.FEELING_ID_PUZZLED:
            return "FEELING_ID_PUZZLED";
        case FeelingID.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
var LanguageID;
(function (LanguageID) {
    LanguageID[LanguageID["LANGUAGE_ID_JAPANESE_UNSPECIFIED"] = 0] = "LANGUAGE_ID_JAPANESE_UNSPECIFIED";
    LanguageID[LanguageID["LANGUAGE_ID_ENGLISH"] = 1] = "LANGUAGE_ID_ENGLISH";
    LanguageID[LanguageID["LANGUAGE_ID_FRENCH"] = 2] = "LANGUAGE_ID_FRENCH";
    LanguageID[LanguageID["LANGUAGE_ID_GERMAN"] = 3] = "LANGUAGE_ID_GERMAN";
    LanguageID[LanguageID["LANGUAGE_ID_ITALIAN"] = 4] = "LANGUAGE_ID_ITALIAN";
    LanguageID[LanguageID["LANGUAGE_ID_SPANISH"] = 5] = "LANGUAGE_ID_SPANISH";
    LanguageID[LanguageID["LANGUAGE_ID_SIMPLIFIED_CHINESE"] = 6] = "LANGUAGE_ID_SIMPLIFIED_CHINESE";
    LanguageID[LanguageID["LANGUAGE_ID_KOREAN"] = 7] = "LANGUAGE_ID_KOREAN";
    LanguageID[LanguageID["LANGUAGE_ID_DUTCH"] = 8] = "LANGUAGE_ID_DUTCH";
    LanguageID[LanguageID["LANGUAGE_ID_PORTUGUESE"] = 9] = "LANGUAGE_ID_PORTUGUESE";
    LanguageID[LanguageID["LANGUAGE_ID_RUSSIAN"] = 10] = "LANGUAGE_ID_RUSSIAN";
    LanguageID[LanguageID["LANGUAGE_ID_TRADITIONAL_CHINESE"] = 11] = "LANGUAGE_ID_TRADITIONAL_CHINESE";
    LanguageID[LanguageID["LANGUAGE_ID_ANY"] = 254] = "LANGUAGE_ID_ANY";
    LanguageID[LanguageID["LANGUAGE_ID_INVALID"] = 255] = "LANGUAGE_ID_INVALID";
    LanguageID[LanguageID["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(LanguageID || (exports.LanguageID = LanguageID = {}));
function languageIDFromJSON(object) {
    switch (object) {
        case 0:
        case "LANGUAGE_ID_JAPANESE_UNSPECIFIED":
            return LanguageID.LANGUAGE_ID_JAPANESE_UNSPECIFIED;
        case 1:
        case "LANGUAGE_ID_ENGLISH":
            return LanguageID.LANGUAGE_ID_ENGLISH;
        case 2:
        case "LANGUAGE_ID_FRENCH":
            return LanguageID.LANGUAGE_ID_FRENCH;
        case 3:
        case "LANGUAGE_ID_GERMAN":
            return LanguageID.LANGUAGE_ID_GERMAN;
        case 4:
        case "LANGUAGE_ID_ITALIAN":
            return LanguageID.LANGUAGE_ID_ITALIAN;
        case 5:
        case "LANGUAGE_ID_SPANISH":
            return LanguageID.LANGUAGE_ID_SPANISH;
        case 6:
        case "LANGUAGE_ID_SIMPLIFIED_CHINESE":
            return LanguageID.LANGUAGE_ID_SIMPLIFIED_CHINESE;
        case 7:
        case "LANGUAGE_ID_KOREAN":
            return LanguageID.LANGUAGE_ID_KOREAN;
        case 8:
        case "LANGUAGE_ID_DUTCH":
            return LanguageID.LANGUAGE_ID_DUTCH;
        case 9:
        case "LANGUAGE_ID_PORTUGUESE":
            return LanguageID.LANGUAGE_ID_PORTUGUESE;
        case 10:
        case "LANGUAGE_ID_RUSSIAN":
            return LanguageID.LANGUAGE_ID_RUSSIAN;
        case 11:
        case "LANGUAGE_ID_TRADITIONAL_CHINESE":
            return LanguageID.LANGUAGE_ID_TRADITIONAL_CHINESE;
        case 254:
        case "LANGUAGE_ID_ANY":
            return LanguageID.LANGUAGE_ID_ANY;
        case 255:
        case "LANGUAGE_ID_INVALID":
            return LanguageID.LANGUAGE_ID_INVALID;
        case -1:
        case "UNRECOGNIZED":
        default:
            return LanguageID.UNRECOGNIZED;
    }
}
function languageIDToJSON(object) {
    switch (object) {
        case LanguageID.LANGUAGE_ID_JAPANESE_UNSPECIFIED:
            return "LANGUAGE_ID_JAPANESE_UNSPECIFIED";
        case LanguageID.LANGUAGE_ID_ENGLISH:
            return "LANGUAGE_ID_ENGLISH";
        case LanguageID.LANGUAGE_ID_FRENCH:
            return "LANGUAGE_ID_FRENCH";
        case LanguageID.LANGUAGE_ID_GERMAN:
            return "LANGUAGE_ID_GERMAN";
        case LanguageID.LANGUAGE_ID_ITALIAN:
            return "LANGUAGE_ID_ITALIAN";
        case LanguageID.LANGUAGE_ID_SPANISH:
            return "LANGUAGE_ID_SPANISH";
        case LanguageID.LANGUAGE_ID_SIMPLIFIED_CHINESE:
            return "LANGUAGE_ID_SIMPLIFIED_CHINESE";
        case LanguageID.LANGUAGE_ID_KOREAN:
            return "LANGUAGE_ID_KOREAN";
        case LanguageID.LANGUAGE_ID_DUTCH:
            return "LANGUAGE_ID_DUTCH";
        case LanguageID.LANGUAGE_ID_PORTUGUESE:
            return "LANGUAGE_ID_PORTUGUESE";
        case LanguageID.LANGUAGE_ID_RUSSIAN:
            return "LANGUAGE_ID_RUSSIAN";
        case LanguageID.LANGUAGE_ID_TRADITIONAL_CHINESE:
            return "LANGUAGE_ID_TRADITIONAL_CHINESE";
        case LanguageID.LANGUAGE_ID_ANY:
            return "LANGUAGE_ID_ANY";
        case LanguageID.LANGUAGE_ID_INVALID:
            return "LANGUAGE_ID_INVALID";
        case LanguageID.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
function createBasePostPainting() {
    return { content: "", size: 0, url: "" };
}
exports.PostPainting = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.content !== "") {
            writer.uint32(10).string(message.content);
        }
        if (message.size !== 0) {
            writer.uint32(16).uint32(message.size);
        }
        if (message.url !== "") {
            writer.uint32(26).string(message.url);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBasePostPainting();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.content = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.size = reader.uint32();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.url = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            content: isSet(object.content) ? globalThis.String(object.content) : "",
            size: isSet(object.size) ? globalThis.Number(object.size) : 0,
            url: isSet(object.url) ? globalThis.String(object.url) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.content !== "") {
            obj.content = message.content;
        }
        if (message.size !== 0) {
            obj.size = Math.round(message.size);
        }
        if (message.url !== "") {
            obj.url = message.url;
        }
        return obj;
    },
    create(base) {
        return exports.PostPainting.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBasePostPainting();
        message.content = object.content ?? "";
        message.size = object.size ?? 0;
        message.url = object.url ?? "";
        return message;
    },
};
function createBasePostScreenshot() {
    return { size: 0, url: "", screenshotAspect: undefined };
}
exports.PostScreenshot = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.size !== 0) {
            writer.uint32(8).uint32(message.size);
        }
        if (message.url !== "") {
            writer.uint32(18).string(message.url);
        }
        if (message.screenshotAspect !== undefined) {
            writer.uint32(26).string(message.screenshotAspect);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBasePostScreenshot();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.size = reader.uint32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.url = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.screenshotAspect = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            size: isSet(object.size) ? globalThis.Number(object.size) : 0,
            url: isSet(object.url) ? globalThis.String(object.url) : "",
            screenshotAspect: isSet(object.screenshotAspect) ? globalThis.String(object.screenshotAspect) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.size !== 0) {
            obj.size = Math.round(message.size);
        }
        if (message.url !== "") {
            obj.url = message.url;
        }
        if (message.screenshotAspect !== undefined) {
            obj.screenshotAspect = message.screenshotAspect;
        }
        return obj;
    },
    create(base) {
        return exports.PostScreenshot.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBasePostScreenshot();
        message.size = object.size ?? 0;
        message.url = object.url ?? "";
        message.screenshotAspect = object.screenshotAspect ?? undefined;
        return message;
    },
};
function createBasePostTopicTag() {
    return { name: "", titleId: "" };
}
exports.PostTopicTag = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.name !== "") {
            writer.uint32(10).string(message.name);
        }
        if (message.titleId !== "") {
            writer.uint32(18).string(message.titleId);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBasePostTopicTag();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.name = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.titleId = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            name: isSet(object.name) ? globalThis.String(object.name) : "",
            titleId: isSet(object.titleId) ? globalThis.String(object.titleId) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.name !== "") {
            obj.name = message.name;
        }
        if (message.titleId !== "") {
            obj.titleId = message.titleId;
        }
        return obj;
    },
    create(base) {
        return exports.PostTopicTag.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBasePostTopicTag();
        message.name = object.name ?? "";
        message.titleId = object.titleId ?? "";
        return message;
    },
};
function createBasePostBinaryData() {
    return { url: "", size: 0 };
}
exports.PostBinaryData = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.url !== "") {
            writer.uint32(10).string(message.url);
        }
        if (message.size !== 0) {
            writer.uint32(16).uint32(message.size);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBasePostBinaryData();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.url = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.size = reader.uint32();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            url: isSet(object.url) ? globalThis.String(object.url) : "",
            size: isSet(object.size) ? globalThis.Number(object.size) : 0,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.url !== "") {
            obj.url = message.url;
        }
        if (message.size !== 0) {
            obj.size = Math.round(message.size);
        }
        return obj;
    },
    create(base) {
        return exports.PostBinaryData.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBasePostBinaryData();
        message.url = object.url ?? "";
        message.size = object.size ?? 0;
        return message;
    },
};
function createBasePostData() {
    return {
        appData: undefined,
        body: undefined,
        communityId: "",
        countryId: 0,
        createdAt: "",
        feelingId: 0,
        id: "",
        isAutopost: false,
        isCommunityPrivateAutopost: false,
        isSpoiler: false,
        isAppJumpable: false,
        empathyCount: 0,
        languageId: 0,
        mii: undefined,
        url: undefined,
        number: 0,
        painting: undefined,
        pid: 0,
        platformId: 0,
        regionId: 0,
        replyCount: 0,
        screenName: "",
        screenshot: undefined,
        topicTag: undefined,
        titleId: "",
        data: undefined,
    };
}
exports.PostData = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.appData !== undefined) {
            writer.uint32(10).string(message.appData);
        }
        if (message.body !== undefined) {
            writer.uint32(18).string(message.body);
        }
        if (message.communityId !== "") {
            writer.uint32(26).string(message.communityId);
        }
        if (message.countryId !== 0) {
            writer.uint32(32).uint32(message.countryId);
        }
        if (message.createdAt !== "") {
            writer.uint32(42).string(message.createdAt);
        }
        if (message.feelingId !== 0) {
            writer.uint32(48).int32(message.feelingId);
        }
        if (message.id !== "") {
            writer.uint32(58).string(message.id);
        }
        if (message.isAutopost !== false) {
            writer.uint32(64).bool(message.isAutopost);
        }
        if (message.isCommunityPrivateAutopost !== false) {
            writer.uint32(72).bool(message.isCommunityPrivateAutopost);
        }
        if (message.isSpoiler !== false) {
            writer.uint32(80).bool(message.isSpoiler);
        }
        if (message.isAppJumpable !== false) {
            writer.uint32(88).bool(message.isAppJumpable);
        }
        if (message.empathyCount !== 0) {
            writer.uint32(96).uint32(message.empathyCount);
        }
        if (message.languageId !== 0) {
            writer.uint32(104).uint32(message.languageId);
        }
        if (message.mii !== undefined) {
            writer.uint32(114).string(message.mii);
        }
        if (message.url !== undefined) {
            writer.uint32(122).string(message.url);
        }
        if (message.number !== 0) {
            writer.uint32(128).uint32(message.number);
        }
        if (message.painting !== undefined) {
            exports.PostPainting.encode(message.painting, writer.uint32(138).fork()).join();
        }
        if (message.pid !== 0) {
            writer.uint32(144).uint32(message.pid);
        }
        if (message.platformId !== 0) {
            writer.uint32(152).uint32(message.platformId);
        }
        if (message.regionId !== 0) {
            writer.uint32(160).uint32(message.regionId);
        }
        if (message.replyCount !== 0) {
            writer.uint32(168).uint32(message.replyCount);
        }
        if (message.screenName !== "") {
            writer.uint32(178).string(message.screenName);
        }
        if (message.screenshot !== undefined) {
            exports.PostScreenshot.encode(message.screenshot, writer.uint32(186).fork()).join();
        }
        if (message.topicTag !== undefined) {
            exports.PostTopicTag.encode(message.topicTag, writer.uint32(194).fork()).join();
        }
        if (message.titleId !== "") {
            writer.uint32(202).string(message.titleId);
        }
        if (message.data !== undefined) {
            exports.PostBinaryData.encode(message.data, writer.uint32(210).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBasePostData();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.appData = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.body = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.communityId = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 32) {
                        break;
                    }
                    message.countryId = reader.uint32();
                    continue;
                }
                case 5: {
                    if (tag !== 42) {
                        break;
                    }
                    message.createdAt = reader.string();
                    continue;
                }
                case 6: {
                    if (tag !== 48) {
                        break;
                    }
                    message.feelingId = reader.int32();
                    continue;
                }
                case 7: {
                    if (tag !== 58) {
                        break;
                    }
                    message.id = reader.string();
                    continue;
                }
                case 8: {
                    if (tag !== 64) {
                        break;
                    }
                    message.isAutopost = reader.bool();
                    continue;
                }
                case 9: {
                    if (tag !== 72) {
                        break;
                    }
                    message.isCommunityPrivateAutopost = reader.bool();
                    continue;
                }
                case 10: {
                    if (tag !== 80) {
                        break;
                    }
                    message.isSpoiler = reader.bool();
                    continue;
                }
                case 11: {
                    if (tag !== 88) {
                        break;
                    }
                    message.isAppJumpable = reader.bool();
                    continue;
                }
                case 12: {
                    if (tag !== 96) {
                        break;
                    }
                    message.empathyCount = reader.uint32();
                    continue;
                }
                case 13: {
                    if (tag !== 104) {
                        break;
                    }
                    message.languageId = reader.uint32();
                    continue;
                }
                case 14: {
                    if (tag !== 114) {
                        break;
                    }
                    message.mii = reader.string();
                    continue;
                }
                case 15: {
                    if (tag !== 122) {
                        break;
                    }
                    message.url = reader.string();
                    continue;
                }
                case 16: {
                    if (tag !== 128) {
                        break;
                    }
                    message.number = reader.uint32();
                    continue;
                }
                case 17: {
                    if (tag !== 138) {
                        break;
                    }
                    message.painting = exports.PostPainting.decode(reader, reader.uint32());
                    continue;
                }
                case 18: {
                    if (tag !== 144) {
                        break;
                    }
                    message.pid = reader.uint32();
                    continue;
                }
                case 19: {
                    if (tag !== 152) {
                        break;
                    }
                    message.platformId = reader.uint32();
                    continue;
                }
                case 20: {
                    if (tag !== 160) {
                        break;
                    }
                    message.regionId = reader.uint32();
                    continue;
                }
                case 21: {
                    if (tag !== 168) {
                        break;
                    }
                    message.replyCount = reader.uint32();
                    continue;
                }
                case 22: {
                    if (tag !== 178) {
                        break;
                    }
                    message.screenName = reader.string();
                    continue;
                }
                case 23: {
                    if (tag !== 186) {
                        break;
                    }
                    message.screenshot = exports.PostScreenshot.decode(reader, reader.uint32());
                    continue;
                }
                case 24: {
                    if (tag !== 194) {
                        break;
                    }
                    message.topicTag = exports.PostTopicTag.decode(reader, reader.uint32());
                    continue;
                }
                case 25: {
                    if (tag !== 202) {
                        break;
                    }
                    message.titleId = reader.string();
                    continue;
                }
                case 26: {
                    if (tag !== 210) {
                        break;
                    }
                    message.data = exports.PostBinaryData.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            appData: isSet(object.appData) ? globalThis.String(object.appData) : undefined,
            body: isSet(object.body) ? globalThis.String(object.body) : undefined,
            communityId: isSet(object.communityId) ? globalThis.String(object.communityId) : "",
            countryId: isSet(object.countryId) ? globalThis.Number(object.countryId) : 0,
            createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "",
            feelingId: isSet(object.feelingId) ? feelingIDFromJSON(object.feelingId) : 0,
            id: isSet(object.id) ? globalThis.String(object.id) : "",
            isAutopost: isSet(object.isAutopost) ? globalThis.Boolean(object.isAutopost) : false,
            isCommunityPrivateAutopost: isSet(object.isCommunityPrivateAutopost)
                ? globalThis.Boolean(object.isCommunityPrivateAutopost)
                : false,
            isSpoiler: isSet(object.isSpoiler) ? globalThis.Boolean(object.isSpoiler) : false,
            isAppJumpable: isSet(object.isAppJumpable) ? globalThis.Boolean(object.isAppJumpable) : false,
            empathyCount: isSet(object.empathyCount) ? globalThis.Number(object.empathyCount) : 0,
            languageId: isSet(object.languageId) ? globalThis.Number(object.languageId) : 0,
            mii: isSet(object.mii) ? globalThis.String(object.mii) : undefined,
            url: isSet(object.url) ? globalThis.String(object.url) : undefined,
            number: isSet(object.number) ? globalThis.Number(object.number) : 0,
            painting: isSet(object.painting) ? exports.PostPainting.fromJSON(object.painting) : undefined,
            pid: isSet(object.pid) ? globalThis.Number(object.pid) : 0,
            platformId: isSet(object.platformId) ? globalThis.Number(object.platformId) : 0,
            regionId: isSet(object.regionId) ? globalThis.Number(object.regionId) : 0,
            replyCount: isSet(object.replyCount) ? globalThis.Number(object.replyCount) : 0,
            screenName: isSet(object.screenName) ? globalThis.String(object.screenName) : "",
            screenshot: isSet(object.screenshot) ? exports.PostScreenshot.fromJSON(object.screenshot) : undefined,
            topicTag: isSet(object.topicTag) ? exports.PostTopicTag.fromJSON(object.topicTag) : undefined,
            titleId: isSet(object.titleId) ? globalThis.String(object.titleId) : "",
            data: isSet(object.data) ? exports.PostBinaryData.fromJSON(object.data) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.appData !== undefined) {
            obj.appData = message.appData;
        }
        if (message.body !== undefined) {
            obj.body = message.body;
        }
        if (message.communityId !== "") {
            obj.communityId = message.communityId;
        }
        if (message.countryId !== 0) {
            obj.countryId = Math.round(message.countryId);
        }
        if (message.createdAt !== "") {
            obj.createdAt = message.createdAt;
        }
        if (message.feelingId !== 0) {
            obj.feelingId = feelingIDToJSON(message.feelingId);
        }
        if (message.id !== "") {
            obj.id = message.id;
        }
        if (message.isAutopost !== false) {
            obj.isAutopost = message.isAutopost;
        }
        if (message.isCommunityPrivateAutopost !== false) {
            obj.isCommunityPrivateAutopost = message.isCommunityPrivateAutopost;
        }
        if (message.isSpoiler !== false) {
            obj.isSpoiler = message.isSpoiler;
        }
        if (message.isAppJumpable !== false) {
            obj.isAppJumpable = message.isAppJumpable;
        }
        if (message.empathyCount !== 0) {
            obj.empathyCount = Math.round(message.empathyCount);
        }
        if (message.languageId !== 0) {
            obj.languageId = Math.round(message.languageId);
        }
        if (message.mii !== undefined) {
            obj.mii = message.mii;
        }
        if (message.url !== undefined) {
            obj.url = message.url;
        }
        if (message.number !== 0) {
            obj.number = Math.round(message.number);
        }
        if (message.painting !== undefined) {
            obj.painting = exports.PostPainting.toJSON(message.painting);
        }
        if (message.pid !== 0) {
            obj.pid = Math.round(message.pid);
        }
        if (message.platformId !== 0) {
            obj.platformId = Math.round(message.platformId);
        }
        if (message.regionId !== 0) {
            obj.regionId = Math.round(message.regionId);
        }
        if (message.replyCount !== 0) {
            obj.replyCount = Math.round(message.replyCount);
        }
        if (message.screenName !== "") {
            obj.screenName = message.screenName;
        }
        if (message.screenshot !== undefined) {
            obj.screenshot = exports.PostScreenshot.toJSON(message.screenshot);
        }
        if (message.topicTag !== undefined) {
            obj.topicTag = exports.PostTopicTag.toJSON(message.topicTag);
        }
        if (message.titleId !== "") {
            obj.titleId = message.titleId;
        }
        if (message.data !== undefined) {
            obj.data = exports.PostBinaryData.toJSON(message.data);
        }
        return obj;
    },
    create(base) {
        return exports.PostData.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBasePostData();
        message.appData = object.appData ?? undefined;
        message.body = object.body ?? undefined;
        message.communityId = object.communityId ?? "";
        message.countryId = object.countryId ?? 0;
        message.createdAt = object.createdAt ?? "";
        message.feelingId = object.feelingId ?? 0;
        message.id = object.id ?? "";
        message.isAutopost = object.isAutopost ?? false;
        message.isCommunityPrivateAutopost = object.isCommunityPrivateAutopost ?? false;
        message.isSpoiler = object.isSpoiler ?? false;
        message.isAppJumpable = object.isAppJumpable ?? false;
        message.empathyCount = object.empathyCount ?? 0;
        message.languageId = object.languageId ?? 0;
        message.mii = object.mii ?? undefined;
        message.url = object.url ?? undefined;
        message.number = object.number ?? 0;
        message.painting = (object.painting !== undefined && object.painting !== null)
            ? exports.PostPainting.fromPartial(object.painting)
            : undefined;
        message.pid = object.pid ?? 0;
        message.platformId = object.platformId ?? 0;
        message.regionId = object.regionId ?? 0;
        message.replyCount = object.replyCount ?? 0;
        message.screenName = object.screenName ?? "";
        message.screenshot = (object.screenshot !== undefined && object.screenshot !== null)
            ? exports.PostScreenshot.fromPartial(object.screenshot)
            : undefined;
        message.topicTag = (object.topicTag !== undefined && object.topicTag !== null)
            ? exports.PostTopicTag.fromPartial(object.topicTag)
            : undefined;
        message.titleId = object.titleId ?? "";
        message.data = (object.data !== undefined && object.data !== null)
            ? exports.PostBinaryData.fromPartial(object.data)
            : undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
