"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: smm/v1/delete_course_rpc.proto
Object.defineProperty(exports, "__esModule", { value: true });
exports.DeleteCourseResponse = exports.DeleteCourseRequest = exports.protobufPackage = void 0;
/* eslint-disable */
const wire_1 = require("@bufbuild/protobuf/wire");
exports.protobufPackage = "smm.v1";
function createBaseDeleteCourseRequest() {
    return { dataId: 0n };
}
exports.DeleteCourseRequest = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.dataId !== 0n) {
            if (BigInt.asUintN(64, message.dataId) !== message.dataId) {
                throw new globalThis.Error("value provided for field message.dataId of type uint64 too large");
            }
            writer.uint32(8).uint64(message.dataId);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseDeleteCourseRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.dataId = reader.uint64();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { dataId: isSet(object.dataId) ? BigInt(object.dataId) : 0n };
    },
    toJSON(message) {
        const obj = {};
        if (message.dataId !== 0n) {
            obj.dataId = message.dataId.toString();
        }
        return obj;
    },
    create(base) {
        return exports.DeleteCourseRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseDeleteCourseRequest();
        message.dataId = object.dataId ?? 0n;
        return message;
    },
};
function createBaseDeleteCourseResponse() {
    return { success: false, courseName: "" };
}
exports.DeleteCourseResponse = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.success !== false) {
            writer.uint32(8).bool(message.success);
        }
        if (message.courseName !== "") {
            writer.uint32(18).string(message.courseName);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseDeleteCourseResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.success = reader.bool();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.courseName = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
            courseName: isSet(object.courseName) ? globalThis.String(object.courseName) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.success !== false) {
            obj.success = message.success;
        }
        if (message.courseName !== "") {
            obj.courseName = message.courseName;
        }
        return obj;
    },
    create(base) {
        return exports.DeleteCourseResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseDeleteCourseResponse();
        message.success = object.success ?? false;
        message.courseName = object.courseName ?? "";
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
