/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter eslint_disable,output_javascript,output_legacy_commonjs,ts_nocheck
// @generated from protobuf file "account/account_service.proto" (package "account", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import type { ExchangeTokenForUserDataRequest } from "./exchange_token_for_user_data";
import type { Empty } from "../google/protobuf/empty";
import type { UpdatePNIDPermissionsRequest } from "./update_pnid_permissions";
import type { GetNEXDataResponse } from "./get_nex_data_rpc";
import type { GetNEXDataRequest } from "./get_nex_data_rpc";
import type { GetNEXPasswordResponse } from "./get_nex_password_rpc";
import type { GetNEXPasswordRequest } from "./get_nex_password_rpc";
import type { GetUserDataResponse } from "./get_user_data_rpc";
import type { GetUserDataRequest } from "./get_user_data_rpc";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service account.Account
 */
export interface IAccountClient {
    /**
     * @generated from protobuf rpc: GetUserData(account.GetUserDataRequest) returns (account.GetUserDataResponse);
     */
    getUserData(input: GetUserDataRequest, options?: RpcOptions): UnaryCall<GetUserDataRequest, GetUserDataResponse>;
    /**
     * @generated from protobuf rpc: GetNEXPassword(account.GetNEXPasswordRequest) returns (account.GetNEXPasswordResponse);
     */
    getNEXPassword(input: GetNEXPasswordRequest, options?: RpcOptions): UnaryCall<GetNEXPasswordRequest, GetNEXPasswordResponse>;
    /**
     * @generated from protobuf rpc: GetNEXData(account.GetNEXDataRequest) returns (account.GetNEXDataResponse);
     */
    getNEXData(input: GetNEXDataRequest, options?: RpcOptions): UnaryCall<GetNEXDataRequest, GetNEXDataResponse>;
    /**
     * @generated from protobuf rpc: UpdatePNIDPermissions(account.UpdatePNIDPermissionsRequest) returns (google.protobuf.Empty);
     */
    updatePNIDPermissions(input: UpdatePNIDPermissionsRequest, options?: RpcOptions): UnaryCall<UpdatePNIDPermissionsRequest, Empty>;
    /**
     * @generated from protobuf rpc: ExchangeTokenForUserData(account.ExchangeTokenForUserDataRequest) returns (account.GetUserDataResponse);
     */
    exchangeTokenForUserData(input: ExchangeTokenForUserDataRequest, options?: RpcOptions): UnaryCall<ExchangeTokenForUserDataRequest, GetUserDataResponse>;
}
/**
 * @generated from protobuf service account.Account
 */
export declare class AccountClient implements IAccountClient, ServiceInfo {
    private readonly _transport;
    typeName: any;
    methods: any;
    options: any;
    constructor(_transport: RpcTransport);
    /**
     * @generated from protobuf rpc: GetUserData(account.GetUserDataRequest) returns (account.GetUserDataResponse);
     */
    getUserData(input: GetUserDataRequest, options?: RpcOptions): UnaryCall<GetUserDataRequest, GetUserDataResponse>;
    /**
     * @generated from protobuf rpc: GetNEXPassword(account.GetNEXPasswordRequest) returns (account.GetNEXPasswordResponse);
     */
    getNEXPassword(input: GetNEXPasswordRequest, options?: RpcOptions): UnaryCall<GetNEXPasswordRequest, GetNEXPasswordResponse>;
    /**
     * @generated from protobuf rpc: GetNEXData(account.GetNEXDataRequest) returns (account.GetNEXDataResponse);
     */
    getNEXData(input: GetNEXDataRequest, options?: RpcOptions): UnaryCall<GetNEXDataRequest, GetNEXDataResponse>;
    /**
     * @generated from protobuf rpc: UpdatePNIDPermissions(account.UpdatePNIDPermissionsRequest) returns (google.protobuf.Empty);
     */
    updatePNIDPermissions(input: UpdatePNIDPermissionsRequest, options?: RpcOptions): UnaryCall<UpdatePNIDPermissionsRequest, Empty>;
    /**
     * @generated from protobuf rpc: ExchangeTokenForUserData(account.ExchangeTokenForUserDataRequest) returns (account.GetUserDataResponse);
     */
    exchangeTokenForUserData(input: ExchangeTokenForUserDataRequest, options?: RpcOptions): UnaryCall<ExchangeTokenForUserDataRequest, GetUserDataResponse>;
}
