/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter eslint_disable,output_javascript,output_legacy_commonjs,ts_nocheck
// @generated from protobuf file "account/get_nex_data_rpc.proto" (package "account", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message account.GetNEXDataRequest
 */
export interface GetNEXDataRequest {
    /**
     * @generated from protobuf field: uint32 pid = 1;
     */
    pid: number;
}
/**
 * @generated from protobuf message account.GetNEXDataResponse
 */
export interface GetNEXDataResponse {
    /**
     * @generated from protobuf field: uint32 pid = 1;
     */
    pid: number;
    /**
     * @generated from protobuf field: string password = 2;
     */
    password: string;
    /**
     * @generated from protobuf field: uint32 owning_pid = 3;
     */
    owningPid: number;
    /**
     * @generated from protobuf field: int32 access_level = 4;
     */
    accessLevel: number;
    /**
     * @generated from protobuf field: string server_access_level = 5;
     */
    serverAccessLevel: string;
    /**
     * @generated from protobuf field: string friend_code = 6;
     */
    friendCode: string;
    /**
     * @generated from protobuf field: account.DeviceType device_type = 7;
     */
    deviceType: DeviceType;
}
/**
 * @generated from protobuf enum account.DeviceType
 */
export declare enum DeviceType {
    /**
     * @generated from protobuf enum value: CTR = 0;
     */
    CTR = 0,
    /**
     * @generated from protobuf enum value: WUP = 1;
     */
    WUP = 1
}
declare class GetNEXDataRequest$Type extends MessageType<GetNEXDataRequest> {
    constructor();
    create(value?: PartialMessage<GetNEXDataRequest>): GetNEXDataRequest;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetNEXDataRequest): GetNEXDataRequest;
    internalBinaryWrite(message: GetNEXDataRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message account.GetNEXDataRequest
 */
export declare const GetNEXDataRequest: GetNEXDataRequest$Type;
declare class GetNEXDataResponse$Type extends MessageType<GetNEXDataResponse> {
    constructor();
    create(value?: PartialMessage<GetNEXDataResponse>): GetNEXDataResponse;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetNEXDataResponse): GetNEXDataResponse;
    internalBinaryWrite(message: GetNEXDataResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message account.GetNEXDataResponse
 */
export declare const GetNEXDataResponse: GetNEXDataResponse$Type;
export {};
