// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: friends/v2/friends_service.proto

package friendsv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_friends_v2_friends_service_proto protoreflect.FileDescriptor

const file_friends_v2_friends_service_proto_rawDesc = "" +
	"\n" +
	" friends/v2/friends_service.proto\x12\n" +
	"friends.v2\x1a*friends/v2/accept_friend_request_rpc.proto\x1a(friends/v2/deny_friend_request_rpc.proto\x1a)friends/v2/get_user_friend_pids_rpc.proto\x1a6friends/v2/get_user_friend_requests_incoming_rpc.proto\x1a-friends/v2/send_user_friend_request_rpc.proto\x1a0friends/v2/send_user_notification_wiiu_rpc.proto2\xb4\x05\n" +
	"\x0eFriendsService\x12w\n" +
	"\x18SendUserNotificationWiiU\x12+.friends.v2.SendUserNotificationWiiURequest\x1a,.friends.v2.SendUserNotificationWiiUResponse\"\x00\x12b\n" +
	"\x11GetUserFriendPIDs\x12$.friends.v2.GetUserFriendPIDsRequest\x1a%.friends.v2.GetUserFriendPIDsResponse\"\x00\x12n\n" +
	"\x15SendUserFriendRequest\x12(.friends.v2.SendUserFriendRequestRequest\x1a).friends.v2.SendUserFriendRequestResponse\"\x00\x12\x86\x01\n" +
	"\x1dGetUserFriendRequestsIncoming\x120.friends.v2.GetUserFriendRequestsIncomingRequest\x1a1.friends.v2.GetUserFriendRequestsIncomingResponse\"\x00\x12h\n" +
	"\x13AcceptFriendRequest\x12&.friends.v2.AcceptFriendRequestRequest\x1a'.friends.v2.AcceptFriendRequestResponse\"\x00\x12b\n" +
	"\x11DenyFriendRequest\x12$.friends.v2.DenyFriendRequestRequest\x1a%.friends.v2.DenyFriendRequestResponse\"\x00B\xa7\x01\n" +
	"\x0ecom.friends.v2B\x13FriendsServiceProtoP\x01Z7github.com/PretendoNetwork/grpc/go/friends/v2;friendsv2\xa2\x02\x03FXX\xaa\x02\n" +
	"Friends.V2\xca\x02\n" +
	"Friends\\V2\xe2\x02\x16Friends\\V2\\GPBMetadata\xea\x02\vFriends::V2b\x06proto3"

var file_friends_v2_friends_service_proto_goTypes = []any{
	(*SendUserNotificationWiiURequest)(nil),       // 0: friends.v2.SendUserNotificationWiiURequest
	(*GetUserFriendPIDsRequest)(nil),              // 1: friends.v2.GetUserFriendPIDsRequest
	(*SendUserFriendRequestRequest)(nil),          // 2: friends.v2.SendUserFriendRequestRequest
	(*GetUserFriendRequestsIncomingRequest)(nil),  // 3: friends.v2.GetUserFriendRequestsIncomingRequest
	(*AcceptFriendRequestRequest)(nil),            // 4: friends.v2.AcceptFriendRequestRequest
	(*DenyFriendRequestRequest)(nil),              // 5: friends.v2.DenyFriendRequestRequest
	(*SendUserNotificationWiiUResponse)(nil),      // 6: friends.v2.SendUserNotificationWiiUResponse
	(*GetUserFriendPIDsResponse)(nil),             // 7: friends.v2.GetUserFriendPIDsResponse
	(*SendUserFriendRequestResponse)(nil),         // 8: friends.v2.SendUserFriendRequestResponse
	(*GetUserFriendRequestsIncomingResponse)(nil), // 9: friends.v2.GetUserFriendRequestsIncomingResponse
	(*AcceptFriendRequestResponse)(nil),           // 10: friends.v2.AcceptFriendRequestResponse
	(*DenyFriendRequestResponse)(nil),             // 11: friends.v2.DenyFriendRequestResponse
}
var file_friends_v2_friends_service_proto_depIdxs = []int32{
	0,  // 0: friends.v2.FriendsService.SendUserNotificationWiiU:input_type -> friends.v2.SendUserNotificationWiiURequest
	1,  // 1: friends.v2.FriendsService.GetUserFriendPIDs:input_type -> friends.v2.GetUserFriendPIDsRequest
	2,  // 2: friends.v2.FriendsService.SendUserFriendRequest:input_type -> friends.v2.SendUserFriendRequestRequest
	3,  // 3: friends.v2.FriendsService.GetUserFriendRequestsIncoming:input_type -> friends.v2.GetUserFriendRequestsIncomingRequest
	4,  // 4: friends.v2.FriendsService.AcceptFriendRequest:input_type -> friends.v2.AcceptFriendRequestRequest
	5,  // 5: friends.v2.FriendsService.DenyFriendRequest:input_type -> friends.v2.DenyFriendRequestRequest
	6,  // 6: friends.v2.FriendsService.SendUserNotificationWiiU:output_type -> friends.v2.SendUserNotificationWiiUResponse
	7,  // 7: friends.v2.FriendsService.GetUserFriendPIDs:output_type -> friends.v2.GetUserFriendPIDsResponse
	8,  // 8: friends.v2.FriendsService.SendUserFriendRequest:output_type -> friends.v2.SendUserFriendRequestResponse
	9,  // 9: friends.v2.FriendsService.GetUserFriendRequestsIncoming:output_type -> friends.v2.GetUserFriendRequestsIncomingResponse
	10, // 10: friends.v2.FriendsService.AcceptFriendRequest:output_type -> friends.v2.AcceptFriendRequestResponse
	11, // 11: friends.v2.FriendsService.DenyFriendRequest:output_type -> friends.v2.DenyFriendRequestResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_friends_v2_friends_service_proto_init() }
func file_friends_v2_friends_service_proto_init() {
	if File_friends_v2_friends_service_proto != nil {
		return
	}
	file_friends_v2_accept_friend_request_rpc_proto_init()
	file_friends_v2_deny_friend_request_rpc_proto_init()
	file_friends_v2_get_user_friend_pids_rpc_proto_init()
	file_friends_v2_get_user_friend_requests_incoming_rpc_proto_init()
	file_friends_v2_send_user_friend_request_rpc_proto_init()
	file_friends_v2_send_user_notification_wiiu_rpc_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_friends_v2_friends_service_proto_rawDesc), len(file_friends_v2_friends_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_friends_v2_friends_service_proto_goTypes,
		DependencyIndexes: file_friends_v2_friends_service_proto_depIdxs,
	}.Build()
	File_friends_v2_friends_service_proto = out.File
	file_friends_v2_friends_service_proto_goTypes = nil
	file_friends_v2_friends_service_proto_depIdxs = nil
}
