// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: account/v2/account_service.proto

/* eslint-disable */
import { type CallContext, type CallOptions } from "nice-grpc-common";
import { ExchangeTokenForUserDataRequest, ExchangeTokenForUserDataResponse } from "./exchange_token_for_user_data";
import { GetNEXDataRequest, GetNEXDataResponse } from "./get_nex_data_rpc";
import { GetNEXPasswordRequest, GetNEXPasswordResponse } from "./get_nex_password_rpc";
import { GetUserDataRequest, GetUserDataResponse } from "./get_user_data_rpc";
import { UpdatePNIDPermissionsRequest, UpdatePNIDPermissionsResponse } from "./update_pnid_permissions";

export const protobufPackage = "account.v2";

export type AccountServiceDefinition = typeof AccountServiceDefinition;
export const AccountServiceDefinition = {
  name: "AccountService",
  fullName: "account.v2.AccountService",
  methods: {
    getUserData: {
      name: "GetUserData",
      requestType: GetUserDataRequest,
      requestStream: false,
      responseType: GetUserDataResponse,
      responseStream: false,
      options: {},
    },
    getNEXPassword: {
      name: "GetNEXPassword",
      requestType: GetNEXPasswordRequest,
      requestStream: false,
      responseType: GetNEXPasswordResponse,
      responseStream: false,
      options: {},
    },
    getNEXData: {
      name: "GetNEXData",
      requestType: GetNEXDataRequest,
      requestStream: false,
      responseType: GetNEXDataResponse,
      responseStream: false,
      options: {},
    },
    updatePNIDPermissions: {
      name: "UpdatePNIDPermissions",
      requestType: UpdatePNIDPermissionsRequest,
      requestStream: false,
      responseType: UpdatePNIDPermissionsResponse,
      responseStream: false,
      options: {},
    },
    exchangeTokenForUserData: {
      name: "ExchangeTokenForUserData",
      requestType: ExchangeTokenForUserDataRequest,
      requestStream: false,
      responseType: ExchangeTokenForUserDataResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface AccountServiceImplementation<CallContextExt = {}> {
  getUserData(
    request: GetUserDataRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetUserDataResponse>>;
  getNEXPassword(
    request: GetNEXPasswordRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetNEXPasswordResponse>>;
  getNEXData(
    request: GetNEXDataRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetNEXDataResponse>>;
  updatePNIDPermissions(
    request: UpdatePNIDPermissionsRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<UpdatePNIDPermissionsResponse>>;
  exchangeTokenForUserData(
    request: ExchangeTokenForUserDataRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ExchangeTokenForUserDataResponse>>;
}

export interface AccountServiceClient<CallOptionsExt = {}> {
  getUserData(
    request: DeepPartial<GetUserDataRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetUserDataResponse>;
  getNEXPassword(
    request: DeepPartial<GetNEXPasswordRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetNEXPasswordResponse>;
  getNEXData(
    request: DeepPartial<GetNEXDataRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetNEXDataResponse>;
  updatePNIDPermissions(
    request: DeepPartial<UpdatePNIDPermissionsRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<UpdatePNIDPermissionsResponse>;
  exchangeTokenForUserData(
    request: DeepPartial<ExchangeTokenForUserDataRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ExchangeTokenForUserDataResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;
