"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: account/v2/audit_log.proto
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuditLog = exports.protobufPackage = void 0;
/* eslint-disable */
const wire_1 = require("@bufbuild/protobuf/wire");
const audit_log_action_type_1 = require("./audit_log_action_type");
exports.protobufPackage = "account.v2";
function createBaseAuditLog() {
    return { id: "", actionType: 0, executedByPid: 0, createdTimestamp: 0n, commentCount: 0, metadataJson: "" };
}
exports.AuditLog = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.id !== "") {
            writer.uint32(10).string(message.id);
        }
        if (message.actionType !== 0) {
            writer.uint32(16).int32(message.actionType);
        }
        if (message.executedByPid !== 0) {
            writer.uint32(24).uint32(message.executedByPid);
        }
        if (message.createdTimestamp !== 0n) {
            if (BigInt.asUintN(64, message.createdTimestamp) !== message.createdTimestamp) {
                throw new globalThis.Error("value provided for field message.createdTimestamp of type uint64 too large");
            }
            writer.uint32(32).uint64(message.createdTimestamp);
        }
        if (message.commentCount !== 0) {
            writer.uint32(40).uint32(message.commentCount);
        }
        if (message.metadataJson !== "") {
            writer.uint32(50).string(message.metadataJson);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseAuditLog();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.id = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.actionType = reader.int32();
                    continue;
                }
                case 3: {
                    if (tag !== 24) {
                        break;
                    }
                    message.executedByPid = reader.uint32();
                    continue;
                }
                case 4: {
                    if (tag !== 32) {
                        break;
                    }
                    message.createdTimestamp = reader.uint64();
                    continue;
                }
                case 5: {
                    if (tag !== 40) {
                        break;
                    }
                    message.commentCount = reader.uint32();
                    continue;
                }
                case 6: {
                    if (tag !== 50) {
                        break;
                    }
                    message.metadataJson = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            id: isSet(object.id) ? globalThis.String(object.id) : "",
            actionType: isSet(object.actionType) ? (0, audit_log_action_type_1.auditLogActionTypeFromJSON)(object.actionType) : 0,
            executedByPid: isSet(object.executedByPid) ? globalThis.Number(object.executedByPid) : 0,
            createdTimestamp: isSet(object.createdTimestamp) ? BigInt(object.createdTimestamp) : 0n,
            commentCount: isSet(object.commentCount) ? globalThis.Number(object.commentCount) : 0,
            metadataJson: isSet(object.metadataJson) ? globalThis.String(object.metadataJson) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.id !== "") {
            obj.id = message.id;
        }
        if (message.actionType !== 0) {
            obj.actionType = (0, audit_log_action_type_1.auditLogActionTypeToJSON)(message.actionType);
        }
        if (message.executedByPid !== 0) {
            obj.executedByPid = Math.round(message.executedByPid);
        }
        if (message.createdTimestamp !== 0n) {
            obj.createdTimestamp = message.createdTimestamp.toString();
        }
        if (message.commentCount !== 0) {
            obj.commentCount = Math.round(message.commentCount);
        }
        if (message.metadataJson !== "") {
            obj.metadataJson = message.metadataJson;
        }
        return obj;
    },
    create(base) {
        return exports.AuditLog.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseAuditLog();
        message.id = object.id ?? "";
        message.actionType = object.actionType ?? 0;
        message.executedByPid = object.executedByPid ?? 0;
        message.createdTimestamp = object.createdTimestamp ?? 0n;
        message.commentCount = object.commentCount ?? 0;
        message.metadataJson = object.metadataJson ?? "";
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
