"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: account/v2/basic_user_info.proto
Object.defineProperty(exports, "__esModule", { value: true });
exports.BasicUserInfo = exports.protobufPackage = void 0;
/* eslint-disable */
const wire_1 = require("@bufbuild/protobuf/wire");
const ban_details_1 = require("./ban_details");
exports.protobufPackage = "account.v2";
function createBaseBasicUserInfo() {
    return { accessBetaServers: false, accessDeveloperServers: false, ban: undefined };
}
exports.BasicUserInfo = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.accessBetaServers !== false) {
            writer.uint32(8).bool(message.accessBetaServers);
        }
        if (message.accessDeveloperServers !== false) {
            writer.uint32(16).bool(message.accessDeveloperServers);
        }
        if (message.ban !== undefined) {
            ban_details_1.Ban.encode(message.ban, writer.uint32(26).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseBasicUserInfo();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.accessBetaServers = reader.bool();
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.accessDeveloperServers = reader.bool();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.ban = ban_details_1.Ban.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            accessBetaServers: isSet(object.accessBetaServers) ? globalThis.Boolean(object.accessBetaServers) : false,
            accessDeveloperServers: isSet(object.accessDeveloperServers)
                ? globalThis.Boolean(object.accessDeveloperServers)
                : false,
            ban: isSet(object.ban) ? ban_details_1.Ban.fromJSON(object.ban) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.accessBetaServers !== false) {
            obj.accessBetaServers = message.accessBetaServers;
        }
        if (message.accessDeveloperServers !== false) {
            obj.accessDeveloperServers = message.accessDeveloperServers;
        }
        if (message.ban !== undefined) {
            obj.ban = ban_details_1.Ban.toJSON(message.ban);
        }
        return obj;
    },
    create(base) {
        return exports.BasicUserInfo.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseBasicUserInfo();
        message.accessBetaServers = object.accessBetaServers ?? false;
        message.accessDeveloperServers = object.accessDeveloperServers ?? false;
        message.ban = (object.ban !== undefined && object.ban !== null) ? ban_details_1.Ban.fromPartial(object.ban) : undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
