// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: account/v2/exchange_independent_service_token_for_user_data_rpc.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { GetPNIDResponse } from "./get_pnid_rpc";
import { NEXAccount } from "./nex_account";
import { TokenInfo } from "./token_info";

export const protobufPackage = "account.v2";

/** TODO - Move this to own file */
export enum IndependentServiceTokenProviderType {
  INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_UNSPECIFIED = 0,
  INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_NASC = 1,
  INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_NNAS = 2,
  UNRECOGNIZED = -1,
}

export function independentServiceTokenProviderTypeFromJSON(object: any): IndependentServiceTokenProviderType {
  switch (object) {
    case 0:
    case "INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_UNSPECIFIED":
      return IndependentServiceTokenProviderType.INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_UNSPECIFIED;
    case 1:
    case "INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_NASC":
      return IndependentServiceTokenProviderType.INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_NASC;
    case 2:
    case "INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_NNAS":
      return IndependentServiceTokenProviderType.INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_NNAS;
    case -1:
    case "UNRECOGNIZED":
    default:
      return IndependentServiceTokenProviderType.UNRECOGNIZED;
  }
}

export function independentServiceTokenProviderTypeToJSON(object: IndependentServiceTokenProviderType): string {
  switch (object) {
    case IndependentServiceTokenProviderType.INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_UNSPECIFIED:
      return "INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_UNSPECIFIED";
    case IndependentServiceTokenProviderType.INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_NASC:
      return "INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_NASC";
    case IndependentServiceTokenProviderType.INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_NNAS:
      return "INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_NNAS";
    case IndependentServiceTokenProviderType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface ExchangeIndependentServiceTokenForUserDataRequest {
  provider: IndependentServiceTokenProviderType;
  /** For NNAS */
  clientId?:
    | string
    | undefined;
  /** For NASC */
  titleIds: string[];
  token: string;
}

export interface ExchangeIndependentServiceTokenForUserDataResponse {
  /** May not be present when using a NASC token */
  pnid?: GetPNIDResponse | undefined;
  nexAccount: NEXAccount | undefined;
  tokenInfo: TokenInfo | undefined;
}

function createBaseExchangeIndependentServiceTokenForUserDataRequest(): ExchangeIndependentServiceTokenForUserDataRequest {
  return { provider: 0, clientId: undefined, titleIds: [], token: "" };
}

export const ExchangeIndependentServiceTokenForUserDataRequest: MessageFns<
  ExchangeIndependentServiceTokenForUserDataRequest
> = {
  encode(
    message: ExchangeIndependentServiceTokenForUserDataRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.provider !== 0) {
      writer.uint32(8).int32(message.provider);
    }
    if (message.clientId !== undefined) {
      writer.uint32(18).string(message.clientId);
    }
    for (const v of message.titleIds) {
      writer.uint32(26).string(v!);
    }
    if (message.token !== "") {
      writer.uint32(34).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExchangeIndependentServiceTokenForUserDataRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExchangeIndependentServiceTokenForUserDataRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.provider = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.titleIds.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExchangeIndependentServiceTokenForUserDataRequest {
    return {
      provider: isSet(object.provider) ? independentServiceTokenProviderTypeFromJSON(object.provider) : 0,
      clientId: isSet(object.clientId) ? globalThis.String(object.clientId) : undefined,
      titleIds: globalThis.Array.isArray(object?.titleIds) ? object.titleIds.map((e: any) => globalThis.String(e)) : [],
      token: isSet(object.token) ? globalThis.String(object.token) : "",
    };
  },

  toJSON(message: ExchangeIndependentServiceTokenForUserDataRequest): unknown {
    const obj: any = {};
    if (message.provider !== 0) {
      obj.provider = independentServiceTokenProviderTypeToJSON(message.provider);
    }
    if (message.clientId !== undefined) {
      obj.clientId = message.clientId;
    }
    if (message.titleIds?.length) {
      obj.titleIds = message.titleIds;
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create(
    base?: DeepPartial<ExchangeIndependentServiceTokenForUserDataRequest>,
  ): ExchangeIndependentServiceTokenForUserDataRequest {
    return ExchangeIndependentServiceTokenForUserDataRequest.fromPartial(base ?? {});
  },
  fromPartial(
    object: DeepPartial<ExchangeIndependentServiceTokenForUserDataRequest>,
  ): ExchangeIndependentServiceTokenForUserDataRequest {
    const message = createBaseExchangeIndependentServiceTokenForUserDataRequest();
    message.provider = object.provider ?? 0;
    message.clientId = object.clientId ?? undefined;
    message.titleIds = object.titleIds?.map((e) => e) || [];
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseExchangeIndependentServiceTokenForUserDataResponse(): ExchangeIndependentServiceTokenForUserDataResponse {
  return { pnid: undefined, nexAccount: undefined, tokenInfo: undefined };
}

export const ExchangeIndependentServiceTokenForUserDataResponse: MessageFns<
  ExchangeIndependentServiceTokenForUserDataResponse
> = {
  encode(
    message: ExchangeIndependentServiceTokenForUserDataResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.pnid !== undefined) {
      GetPNIDResponse.encode(message.pnid, writer.uint32(10).fork()).join();
    }
    if (message.nexAccount !== undefined) {
      NEXAccount.encode(message.nexAccount, writer.uint32(18).fork()).join();
    }
    if (message.tokenInfo !== undefined) {
      TokenInfo.encode(message.tokenInfo, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExchangeIndependentServiceTokenForUserDataResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExchangeIndependentServiceTokenForUserDataResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pnid = GetPNIDResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nexAccount = NEXAccount.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.tokenInfo = TokenInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExchangeIndependentServiceTokenForUserDataResponse {
    return {
      pnid: isSet(object.pnid) ? GetPNIDResponse.fromJSON(object.pnid) : undefined,
      nexAccount: isSet(object.nexAccount) ? NEXAccount.fromJSON(object.nexAccount) : undefined,
      tokenInfo: isSet(object.tokenInfo) ? TokenInfo.fromJSON(object.tokenInfo) : undefined,
    };
  },

  toJSON(message: ExchangeIndependentServiceTokenForUserDataResponse): unknown {
    const obj: any = {};
    if (message.pnid !== undefined) {
      obj.pnid = GetPNIDResponse.toJSON(message.pnid);
    }
    if (message.nexAccount !== undefined) {
      obj.nexAccount = NEXAccount.toJSON(message.nexAccount);
    }
    if (message.tokenInfo !== undefined) {
      obj.tokenInfo = TokenInfo.toJSON(message.tokenInfo);
    }
    return obj;
  },

  create(
    base?: DeepPartial<ExchangeIndependentServiceTokenForUserDataResponse>,
  ): ExchangeIndependentServiceTokenForUserDataResponse {
    return ExchangeIndependentServiceTokenForUserDataResponse.fromPartial(base ?? {});
  },
  fromPartial(
    object: DeepPartial<ExchangeIndependentServiceTokenForUserDataResponse>,
  ): ExchangeIndependentServiceTokenForUserDataResponse {
    const message = createBaseExchangeIndependentServiceTokenForUserDataResponse();
    message.pnid = (object.pnid !== undefined && object.pnid !== null)
      ? GetPNIDResponse.fromPartial(object.pnid)
      : undefined;
    message.nexAccount = (object.nexAccount !== undefined && object.nexAccount !== null)
      ? NEXAccount.fromPartial(object.nexAccount)
      : undefined;
    message.tokenInfo = (object.tokenInfo !== undefined && object.tokenInfo !== null)
      ? TokenInfo.fromPartial(object.tokenInfo)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
