"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: account/v2/exchange_independent_service_token_for_user_data_rpc.proto
Object.defineProperty(exports, "__esModule", { value: true });
exports.ExchangeIndependentServiceTokenForUserDataResponse = exports.ExchangeIndependentServiceTokenForUserDataRequest = exports.IndependentServiceTokenProviderType = exports.protobufPackage = void 0;
exports.independentServiceTokenProviderTypeFromJSON = independentServiceTokenProviderTypeFromJSON;
exports.independentServiceTokenProviderTypeToJSON = independentServiceTokenProviderTypeToJSON;
/* eslint-disable */
const wire_1 = require("@bufbuild/protobuf/wire");
const get_pnid_rpc_1 = require("./get_pnid_rpc");
const nex_account_1 = require("./nex_account");
const token_info_1 = require("./token_info");
exports.protobufPackage = "account.v2";
/** TODO - Move this to own file */
var IndependentServiceTokenProviderType;
(function (IndependentServiceTokenProviderType) {
    IndependentServiceTokenProviderType[IndependentServiceTokenProviderType["INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_UNSPECIFIED"] = 0] = "INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_UNSPECIFIED";
    IndependentServiceTokenProviderType[IndependentServiceTokenProviderType["INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_NASC"] = 1] = "INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_NASC";
    IndependentServiceTokenProviderType[IndependentServiceTokenProviderType["INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_NNAS"] = 2] = "INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_NNAS";
    IndependentServiceTokenProviderType[IndependentServiceTokenProviderType["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(IndependentServiceTokenProviderType || (exports.IndependentServiceTokenProviderType = IndependentServiceTokenProviderType = {}));
function independentServiceTokenProviderTypeFromJSON(object) {
    switch (object) {
        case 0:
        case "INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_UNSPECIFIED":
            return IndependentServiceTokenProviderType.INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_UNSPECIFIED;
        case 1:
        case "INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_NASC":
            return IndependentServiceTokenProviderType.INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_NASC;
        case 2:
        case "INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_NNAS":
            return IndependentServiceTokenProviderType.INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_NNAS;
        case -1:
        case "UNRECOGNIZED":
        default:
            return IndependentServiceTokenProviderType.UNRECOGNIZED;
    }
}
function independentServiceTokenProviderTypeToJSON(object) {
    switch (object) {
        case IndependentServiceTokenProviderType.INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_UNSPECIFIED:
            return "INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_UNSPECIFIED";
        case IndependentServiceTokenProviderType.INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_NASC:
            return "INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_NASC";
        case IndependentServiceTokenProviderType.INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_NNAS:
            return "INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_NNAS";
        case IndependentServiceTokenProviderType.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
function createBaseExchangeIndependentServiceTokenForUserDataRequest() {
    return { provider: 0, clientId: undefined, titleIds: [], token: "" };
}
exports.ExchangeIndependentServiceTokenForUserDataRequest = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.provider !== 0) {
            writer.uint32(8).int32(message.provider);
        }
        if (message.clientId !== undefined) {
            writer.uint32(18).string(message.clientId);
        }
        for (const v of message.titleIds) {
            writer.uint32(26).string(v);
        }
        if (message.token !== "") {
            writer.uint32(34).string(message.token);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseExchangeIndependentServiceTokenForUserDataRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.provider = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.clientId = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.titleIds.push(reader.string());
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.token = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            provider: isSet(object.provider) ? independentServiceTokenProviderTypeFromJSON(object.provider) : 0,
            clientId: isSet(object.clientId) ? globalThis.String(object.clientId) : undefined,
            titleIds: globalThis.Array.isArray(object?.titleIds) ? object.titleIds.map((e) => globalThis.String(e)) : [],
            token: isSet(object.token) ? globalThis.String(object.token) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.provider !== 0) {
            obj.provider = independentServiceTokenProviderTypeToJSON(message.provider);
        }
        if (message.clientId !== undefined) {
            obj.clientId = message.clientId;
        }
        if (message.titleIds?.length) {
            obj.titleIds = message.titleIds;
        }
        if (message.token !== "") {
            obj.token = message.token;
        }
        return obj;
    },
    create(base) {
        return exports.ExchangeIndependentServiceTokenForUserDataRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseExchangeIndependentServiceTokenForUserDataRequest();
        message.provider = object.provider ?? 0;
        message.clientId = object.clientId ?? undefined;
        message.titleIds = object.titleIds?.map((e) => e) || [];
        message.token = object.token ?? "";
        return message;
    },
};
function createBaseExchangeIndependentServiceTokenForUserDataResponse() {
    return { pnid: undefined, nexAccount: undefined, tokenInfo: undefined };
}
exports.ExchangeIndependentServiceTokenForUserDataResponse = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.pnid !== undefined) {
            get_pnid_rpc_1.GetPNIDResponse.encode(message.pnid, writer.uint32(10).fork()).join();
        }
        if (message.nexAccount !== undefined) {
            nex_account_1.NEXAccount.encode(message.nexAccount, writer.uint32(18).fork()).join();
        }
        if (message.tokenInfo !== undefined) {
            token_info_1.TokenInfo.encode(message.tokenInfo, writer.uint32(26).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseExchangeIndependentServiceTokenForUserDataResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.pnid = get_pnid_rpc_1.GetPNIDResponse.decode(reader, reader.uint32());
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.nexAccount = nex_account_1.NEXAccount.decode(reader, reader.uint32());
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.tokenInfo = token_info_1.TokenInfo.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            pnid: isSet(object.pnid) ? get_pnid_rpc_1.GetPNIDResponse.fromJSON(object.pnid) : undefined,
            nexAccount: isSet(object.nexAccount) ? nex_account_1.NEXAccount.fromJSON(object.nexAccount) : undefined,
            tokenInfo: isSet(object.tokenInfo) ? token_info_1.TokenInfo.fromJSON(object.tokenInfo) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.pnid !== undefined) {
            obj.pnid = get_pnid_rpc_1.GetPNIDResponse.toJSON(message.pnid);
        }
        if (message.nexAccount !== undefined) {
            obj.nexAccount = nex_account_1.NEXAccount.toJSON(message.nexAccount);
        }
        if (message.tokenInfo !== undefined) {
            obj.tokenInfo = token_info_1.TokenInfo.toJSON(message.tokenInfo);
        }
        return obj;
    },
    create(base) {
        return exports.ExchangeIndependentServiceTokenForUserDataResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseExchangeIndependentServiceTokenForUserDataResponse();
        message.pnid = (object.pnid !== undefined && object.pnid !== null)
            ? get_pnid_rpc_1.GetPNIDResponse.fromPartial(object.pnid)
            : undefined;
        message.nexAccount = (object.nexAccount !== undefined && object.nexAccount !== null)
            ? nex_account_1.NEXAccount.fromPartial(object.nexAccount)
            : undefined;
        message.tokenInfo = (object.tokenInfo !== undefined && object.tokenInfo !== null)
            ? token_info_1.TokenInfo.fromPartial(object.tokenInfo)
            : undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
