"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: account/v2/get_nex_account_rpc.proto
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetNEXAccountResponse = exports.GetNEXAccountRequest = exports.protobufPackage = void 0;
/* eslint-disable */
const wire_1 = require("@bufbuild/protobuf/wire");
const nex_account_1 = require("./nex_account");
exports.protobufPackage = "account.v2";
function createBaseGetNEXAccountRequest() {
    return { pid: 0 };
}
exports.GetNEXAccountRequest = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.pid !== 0) {
            writer.uint32(8).uint32(message.pid);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGetNEXAccountRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.pid = reader.uint32();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { pid: isSet(object.pid) ? globalThis.Number(object.pid) : 0 };
    },
    toJSON(message) {
        const obj = {};
        if (message.pid !== 0) {
            obj.pid = Math.round(message.pid);
        }
        return obj;
    },
    create(base) {
        return exports.GetNEXAccountRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseGetNEXAccountRequest();
        message.pid = object.pid ?? 0;
        return message;
    },
};
function createBaseGetNEXAccountResponse() {
    return { nexAccount: undefined };
}
exports.GetNEXAccountResponse = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.nexAccount !== undefined) {
            nex_account_1.NEXAccount.encode(message.nexAccount, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGetNEXAccountResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.nexAccount = nex_account_1.NEXAccount.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { nexAccount: isSet(object.nexAccount) ? nex_account_1.NEXAccount.fromJSON(object.nexAccount) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.nexAccount !== undefined) {
            obj.nexAccount = nex_account_1.NEXAccount.toJSON(message.nexAccount);
        }
        return obj;
    },
    create(base) {
        return exports.GetNEXAccountResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseGetNEXAccountResponse();
        message.nexAccount = (object.nexAccount !== undefined && object.nexAccount !== null)
            ? nex_account_1.NEXAccount.fromPartial(object.nexAccount)
            : undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
