"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: account/v2/list_audit_logs_rpc.proto
Object.defineProperty(exports, "__esModule", { value: true });
exports.ListAuditLogsResponse = exports.ListAuditLogsRequest_Filter = exports.ListAuditLogsRequest = exports.protobufPackage = void 0;
/* eslint-disable */
const wire_1 = require("@bufbuild/protobuf/wire");
const audit_log_1 = require("./audit_log");
const audit_log_action_type_1 = require("./audit_log_action_type");
const page_1 = require("./page");
exports.protobufPackage = "account.v2";
function createBaseListAuditLogsRequest() {
    return { page: undefined, filter: undefined };
}
exports.ListAuditLogsRequest = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.page !== undefined) {
            page_1.PageInput.encode(message.page, writer.uint32(10).fork()).join();
        }
        if (message.filter !== undefined) {
            exports.ListAuditLogsRequest_Filter.encode(message.filter, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseListAuditLogsRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.page = page_1.PageInput.decode(reader, reader.uint32());
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.filter = exports.ListAuditLogsRequest_Filter.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            page: isSet(object.page) ? page_1.PageInput.fromJSON(object.page) : undefined,
            filter: isSet(object.filter) ? exports.ListAuditLogsRequest_Filter.fromJSON(object.filter) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.page !== undefined) {
            obj.page = page_1.PageInput.toJSON(message.page);
        }
        if (message.filter !== undefined) {
            obj.filter = exports.ListAuditLogsRequest_Filter.toJSON(message.filter);
        }
        return obj;
    },
    create(base) {
        return exports.ListAuditLogsRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseListAuditLogsRequest();
        message.page = (object.page !== undefined && object.page !== null) ? page_1.PageInput.fromPartial(object.page) : undefined;
        message.filter = (object.filter !== undefined && object.filter !== null)
            ? exports.ListAuditLogsRequest_Filter.fromPartial(object.filter)
            : undefined;
        return message;
    },
};
function createBaseListAuditLogsRequest_Filter() {
    return { executedByPid: [], actionType: [], extraJson: undefined };
}
exports.ListAuditLogsRequest_Filter = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        writer.uint32(10).fork();
        for (const v of message.executedByPid) {
            writer.uint32(v);
        }
        writer.join();
        writer.uint32(18).fork();
        for (const v of message.actionType) {
            writer.int32(v);
        }
        writer.join();
        if (message.extraJson !== undefined) {
            writer.uint32(26).string(message.extraJson);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseListAuditLogsRequest_Filter();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag === 8) {
                        message.executedByPid.push(reader.uint32());
                        continue;
                    }
                    if (tag === 10) {
                        const end2 = reader.uint32() + reader.pos;
                        while (reader.pos < end2) {
                            message.executedByPid.push(reader.uint32());
                        }
                        continue;
                    }
                    break;
                }
                case 2: {
                    if (tag === 16) {
                        message.actionType.push(reader.int32());
                        continue;
                    }
                    if (tag === 18) {
                        const end2 = reader.uint32() + reader.pos;
                        while (reader.pos < end2) {
                            message.actionType.push(reader.int32());
                        }
                        continue;
                    }
                    break;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.extraJson = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            executedByPid: globalThis.Array.isArray(object?.executedByPid)
                ? object.executedByPid.map((e) => globalThis.Number(e))
                : [],
            actionType: globalThis.Array.isArray(object?.actionType)
                ? object.actionType.map((e) => (0, audit_log_action_type_1.auditLogActionTypeFromJSON)(e))
                : [],
            extraJson: isSet(object.extraJson) ? globalThis.String(object.extraJson) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.executedByPid?.length) {
            obj.executedByPid = message.executedByPid.map((e) => Math.round(e));
        }
        if (message.actionType?.length) {
            obj.actionType = message.actionType.map((e) => (0, audit_log_action_type_1.auditLogActionTypeToJSON)(e));
        }
        if (message.extraJson !== undefined) {
            obj.extraJson = message.extraJson;
        }
        return obj;
    },
    create(base) {
        return exports.ListAuditLogsRequest_Filter.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseListAuditLogsRequest_Filter();
        message.executedByPid = object.executedByPid?.map((e) => e) || [];
        message.actionType = object.actionType?.map((e) => e) || [];
        message.extraJson = object.extraJson ?? undefined;
        return message;
    },
};
function createBaseListAuditLogsResponse() {
    return { page: undefined, items: [] };
}
exports.ListAuditLogsResponse = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.page !== undefined) {
            page_1.PageResults.encode(message.page, writer.uint32(10).fork()).join();
        }
        for (const v of message.items) {
            audit_log_1.AuditLog.encode(v, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseListAuditLogsResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.page = page_1.PageResults.decode(reader, reader.uint32());
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.items.push(audit_log_1.AuditLog.decode(reader, reader.uint32()));
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            page: isSet(object.page) ? page_1.PageResults.fromJSON(object.page) : undefined,
            items: globalThis.Array.isArray(object?.items) ? object.items.map((e) => audit_log_1.AuditLog.fromJSON(e)) : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.page !== undefined) {
            obj.page = page_1.PageResults.toJSON(message.page);
        }
        if (message.items?.length) {
            obj.items = message.items.map((e) => audit_log_1.AuditLog.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return exports.ListAuditLogsResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseListAuditLogsResponse();
        message.page = (object.page !== undefined && object.page !== null)
            ? page_1.PageResults.fromPartial(object.page)
            : undefined;
        message.items = object.items?.map((e) => audit_log_1.AuditLog.fromPartial(e)) || [];
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
