"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: account/v2/list_ban_comments_rpc.proto
Object.defineProperty(exports, "__esModule", { value: true });
exports.ListBanCommentsResponse = exports.ListBanCommentsRequest = exports.protobufPackage = void 0;
/* eslint-disable */
const wire_1 = require("@bufbuild/protobuf/wire");
const comment_1 = require("./comment");
exports.protobufPackage = "account.v2";
function createBaseListBanCommentsRequest() {
    return { id: "" };
}
exports.ListBanCommentsRequest = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.id !== "") {
            writer.uint32(10).string(message.id);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseListBanCommentsRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.id = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
    },
    toJSON(message) {
        const obj = {};
        if (message.id !== "") {
            obj.id = message.id;
        }
        return obj;
    },
    create(base) {
        return exports.ListBanCommentsRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseListBanCommentsRequest();
        message.id = object.id ?? "";
        return message;
    },
};
function createBaseListBanCommentsResponse() {
    return { items: [] };
}
exports.ListBanCommentsResponse = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        for (const v of message.items) {
            comment_1.Comment.encode(v, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseListBanCommentsResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.items.push(comment_1.Comment.decode(reader, reader.uint32()));
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { items: globalThis.Array.isArray(object?.items) ? object.items.map((e) => comment_1.Comment.fromJSON(e)) : [] };
    },
    toJSON(message) {
        const obj = {};
        if (message.items?.length) {
            obj.items = message.items.map((e) => comment_1.Comment.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return exports.ListBanCommentsResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseListBanCommentsResponse();
        message.items = object.items?.map((e) => comment_1.Comment.fromPartial(e)) || [];
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
