"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: account/v2/list_nex_accounts_rpc.proto
Object.defineProperty(exports, "__esModule", { value: true });
exports.ListNEXAccountsResponse = exports.ListNEXAccountsRequest_Filter = exports.ListNEXAccountsRequest = exports.protobufPackage = void 0;
/* eslint-disable */
const wire_1 = require("@bufbuild/protobuf/wire");
const nex_account_1 = require("./nex_account");
const page_1 = require("./page");
exports.protobufPackage = "account.v2";
function createBaseListNEXAccountsRequest() {
    return { page: undefined, filter: undefined };
}
exports.ListNEXAccountsRequest = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.page !== undefined) {
            page_1.PageInput.encode(message.page, writer.uint32(10).fork()).join();
        }
        if (message.filter !== undefined) {
            exports.ListNEXAccountsRequest_Filter.encode(message.filter, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseListNEXAccountsRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.page = page_1.PageInput.decode(reader, reader.uint32());
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.filter = exports.ListNEXAccountsRequest_Filter.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            page: isSet(object.page) ? page_1.PageInput.fromJSON(object.page) : undefined,
            filter: isSet(object.filter) ? exports.ListNEXAccountsRequest_Filter.fromJSON(object.filter) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.page !== undefined) {
            obj.page = page_1.PageInput.toJSON(message.page);
        }
        if (message.filter !== undefined) {
            obj.filter = exports.ListNEXAccountsRequest_Filter.toJSON(message.filter);
        }
        return obj;
    },
    create(base) {
        return exports.ListNEXAccountsRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseListNEXAccountsRequest();
        message.page = (object.page !== undefined && object.page !== null) ? page_1.PageInput.fromPartial(object.page) : undefined;
        message.filter = (object.filter !== undefined && object.filter !== null)
            ? exports.ListNEXAccountsRequest_Filter.fromPartial(object.filter)
            : undefined;
        return message;
    },
};
function createBaseListNEXAccountsRequest_Filter() {
    return { pid: undefined, friendCode: undefined, extraJson: undefined };
}
exports.ListNEXAccountsRequest_Filter = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.pid !== undefined) {
            writer.uint32(8).uint32(message.pid);
        }
        if (message.friendCode !== undefined) {
            writer.uint32(16).uint32(message.friendCode);
        }
        if (message.extraJson !== undefined) {
            writer.uint32(26).string(message.extraJson);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseListNEXAccountsRequest_Filter();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.pid = reader.uint32();
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.friendCode = reader.uint32();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.extraJson = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            pid: isSet(object.pid) ? globalThis.Number(object.pid) : undefined,
            friendCode: isSet(object.friendCode) ? globalThis.Number(object.friendCode) : undefined,
            extraJson: isSet(object.extraJson) ? globalThis.String(object.extraJson) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.pid !== undefined) {
            obj.pid = Math.round(message.pid);
        }
        if (message.friendCode !== undefined) {
            obj.friendCode = Math.round(message.friendCode);
        }
        if (message.extraJson !== undefined) {
            obj.extraJson = message.extraJson;
        }
        return obj;
    },
    create(base) {
        return exports.ListNEXAccountsRequest_Filter.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseListNEXAccountsRequest_Filter();
        message.pid = object.pid ?? undefined;
        message.friendCode = object.friendCode ?? undefined;
        message.extraJson = object.extraJson ?? undefined;
        return message;
    },
};
function createBaseListNEXAccountsResponse() {
    return { page: undefined, items: [] };
}
exports.ListNEXAccountsResponse = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.page !== undefined) {
            page_1.PageResults.encode(message.page, writer.uint32(10).fork()).join();
        }
        for (const v of message.items) {
            nex_account_1.NEXAccount.encode(v, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseListNEXAccountsResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.page = page_1.PageResults.decode(reader, reader.uint32());
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.items.push(nex_account_1.NEXAccount.decode(reader, reader.uint32()));
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            page: isSet(object.page) ? page_1.PageResults.fromJSON(object.page) : undefined,
            items: globalThis.Array.isArray(object?.items) ? object.items.map((e) => nex_account_1.NEXAccount.fromJSON(e)) : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.page !== undefined) {
            obj.page = page_1.PageResults.toJSON(message.page);
        }
        if (message.items?.length) {
            obj.items = message.items.map((e) => nex_account_1.NEXAccount.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return exports.ListNEXAccountsResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseListNEXAccountsResponse();
        message.page = (object.page !== undefined && object.page !== null)
            ? page_1.PageResults.fromPartial(object.page)
            : undefined;
        message.items = object.items?.map((e) => nex_account_1.NEXAccount.fromPartial(e)) || [];
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
