"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: account/v2/update_device_rpc.proto
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpdateDeviceResponse = exports.UpdateDeviceRequest = exports.protobufPackage = void 0;
/* eslint-disable */
const wire_1 = require("@bufbuild/protobuf/wire");
const device_1 = require("./device");
exports.protobufPackage = "account.v2";
function createBaseUpdateDeviceRequest() {
    return { deviceId: 0, serverAccessLevel: undefined, accessLevel: undefined };
}
exports.UpdateDeviceRequest = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.deviceId !== 0) {
            writer.uint32(8).uint32(message.deviceId);
        }
        if (message.serverAccessLevel !== undefined) {
            writer.uint32(18).string(message.serverAccessLevel);
        }
        if (message.accessLevel !== undefined) {
            writer.uint32(24).int32(message.accessLevel);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseUpdateDeviceRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.deviceId = reader.uint32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.serverAccessLevel = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 24) {
                        break;
                    }
                    message.accessLevel = reader.int32();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            deviceId: isSet(object.deviceId) ? globalThis.Number(object.deviceId) : 0,
            serverAccessLevel: isSet(object.serverAccessLevel) ? globalThis.String(object.serverAccessLevel) : undefined,
            accessLevel: isSet(object.accessLevel) ? globalThis.Number(object.accessLevel) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.deviceId !== 0) {
            obj.deviceId = Math.round(message.deviceId);
        }
        if (message.serverAccessLevel !== undefined) {
            obj.serverAccessLevel = message.serverAccessLevel;
        }
        if (message.accessLevel !== undefined) {
            obj.accessLevel = Math.round(message.accessLevel);
        }
        return obj;
    },
    create(base) {
        return exports.UpdateDeviceRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseUpdateDeviceRequest();
        message.deviceId = object.deviceId ?? 0;
        message.serverAccessLevel = object.serverAccessLevel ?? undefined;
        message.accessLevel = object.accessLevel ?? undefined;
        return message;
    },
};
function createBaseUpdateDeviceResponse() {
    return { device: undefined };
}
exports.UpdateDeviceResponse = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.device !== undefined) {
            device_1.Device.encode(message.device, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseUpdateDeviceResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.device = device_1.Device.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { device: isSet(object.device) ? device_1.Device.fromJSON(object.device) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.device !== undefined) {
            obj.device = device_1.Device.toJSON(message.device);
        }
        return obj;
    },
    create(base) {
        return exports.UpdateDeviceResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseUpdateDeviceResponse();
        message.device = (object.device !== undefined && object.device !== null)
            ? device_1.Device.fromPartial(object.device)
            : undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
