// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nex/v1/nex_service.proto

package nexv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_nex_v1_nex_service_proto protoreflect.FileDescriptor

const file_nex_v1_nex_service_proto_rawDesc = "" +
	"\n" +
	"\x18nex/v1/nex_service.proto\x12\x06nex.v1\x1a\x1anex/v1/get_stats_rpc.proto\x1a\x1anex/v1/kick_user_rpc.proto\x1a%nex/v1/kick_user_aggressive_rpc.proto\x1a%nex/v1/kill_user_connection_rpc.proto2\xce\x02\n" +
	"\fNEXServiceV1\x12?\n" +
	"\bGetStats\x12\x17.nex.v1.GetStatsRequest\x1a\x18.nex.v1.GetStatsResponse\"\x00\x12?\n" +
	"\bKickUser\x12\x17.nex.v1.KickUserRequest\x1a\x18.nex.v1.KickUserResponse\"\x00\x12]\n" +
	"\x12KickUserAggressive\x12!.nex.v1.KickUserAggressiveRequest\x1a\".nex.v1.KickUserAggressiveResponse\"\x00\x12]\n" +
	"\x12KillUserConnection\x12!.nex.v1.KillUserConnectionRequest\x1a\".nex.v1.KillUserConnectionResponse\"\x00B\x87\x01\n" +
	"\n" +
	"com.nex.v1B\x0fNexServiceProtoP\x01Z/github.com/PretendoNetwork/grpc/go/nex/v1;nexv1\xa2\x02\x03NXX\xaa\x02\x06Nex.V1\xca\x02\x06Nex\\V1\xe2\x02\x12Nex\\V1\\GPBMetadata\xea\x02\aNex::V1b\x06proto3"

var file_nex_v1_nex_service_proto_goTypes = []any{
	(*GetStatsRequest)(nil),            // 0: nex.v1.GetStatsRequest
	(*KickUserRequest)(nil),            // 1: nex.v1.KickUserRequest
	(*KickUserAggressiveRequest)(nil),  // 2: nex.v1.KickUserAggressiveRequest
	(*KillUserConnectionRequest)(nil),  // 3: nex.v1.KillUserConnectionRequest
	(*GetStatsResponse)(nil),           // 4: nex.v1.GetStatsResponse
	(*KickUserResponse)(nil),           // 5: nex.v1.KickUserResponse
	(*KickUserAggressiveResponse)(nil), // 6: nex.v1.KickUserAggressiveResponse
	(*KillUserConnectionResponse)(nil), // 7: nex.v1.KillUserConnectionResponse
}
var file_nex_v1_nex_service_proto_depIdxs = []int32{
	0, // 0: nex.v1.NEXServiceV1.GetStats:input_type -> nex.v1.GetStatsRequest
	1, // 1: nex.v1.NEXServiceV1.KickUser:input_type -> nex.v1.KickUserRequest
	2, // 2: nex.v1.NEXServiceV1.KickUserAggressive:input_type -> nex.v1.KickUserAggressiveRequest
	3, // 3: nex.v1.NEXServiceV1.KillUserConnection:input_type -> nex.v1.KillUserConnectionRequest
	4, // 4: nex.v1.NEXServiceV1.GetStats:output_type -> nex.v1.GetStatsResponse
	5, // 5: nex.v1.NEXServiceV1.KickUser:output_type -> nex.v1.KickUserResponse
	6, // 6: nex.v1.NEXServiceV1.KickUserAggressive:output_type -> nex.v1.KickUserAggressiveResponse
	7, // 7: nex.v1.NEXServiceV1.KillUserConnection:output_type -> nex.v1.KillUserConnectionResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nex_v1_nex_service_proto_init() }
func file_nex_v1_nex_service_proto_init() {
	if File_nex_v1_nex_service_proto != nil {
		return
	}
	file_nex_v1_get_stats_rpc_proto_init()
	file_nex_v1_kick_user_rpc_proto_init()
	file_nex_v1_kick_user_aggressive_rpc_proto_init()
	file_nex_v1_kill_user_connection_rpc_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nex_v1_nex_service_proto_rawDesc), len(file_nex_v1_nex_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nex_v1_nex_service_proto_goTypes,
		DependencyIndexes: file_nex_v1_nex_service_proto_depIdxs,
	}.Build()
	File_nex_v1_nex_service_proto = out.File
	file_nex_v1_nex_service_proto_goTypes = nil
	file_nex_v1_nex_service_proto_depIdxs = nil
}
