// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: nex/v1/nex_service.proto

package nexv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NEXServiceV1_GetStats_FullMethodName           = "/nex.v1.NEXServiceV1/GetStats"
	NEXServiceV1_KickUser_FullMethodName           = "/nex.v1.NEXServiceV1/KickUser"
	NEXServiceV1_KickUserAggressive_FullMethodName = "/nex.v1.NEXServiceV1/KickUserAggressive"
	NEXServiceV1_KillUserConnection_FullMethodName = "/nex.v1.NEXServiceV1/KillUserConnection"
	NEXServiceV1_GetActiveMatches_FullMethodName   = "/nex.v1.NEXServiceV1/GetActiveMatches"
)

// NEXServiceV1Client is the client API for NEXServiceV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NEXServiceV1Client interface {
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	// Remove a user gracefully using the built in DISCONNECT system
	KickUser(ctx context.Context, in *KickUserRequest, opts ...grpc.CallOption) (*KickUserResponse, error)
	// Remove a user aggressively using methods like killing the internal RC4 stream along with graceful methods
	KickUserAggressive(ctx context.Context, in *KickUserAggressiveRequest, opts ...grpc.CallOption) (*KickUserAggressiveResponse, error)
	// Remove a user by any means necessary
	KillUserConnection(ctx context.Context, in *KillUserConnectionRequest, opts ...grpc.CallOption) (*KillUserConnectionResponse, error)
	// Fetch active matches
	GetActiveMatches(ctx context.Context, in *GetActiveMatchesRequest, opts ...grpc.CallOption) (*GetActiveMatchesResponse, error)
}

type nEXServiceV1Client struct {
	cc grpc.ClientConnInterface
}

func NewNEXServiceV1Client(cc grpc.ClientConnInterface) NEXServiceV1Client {
	return &nEXServiceV1Client{cc}
}

func (c *nEXServiceV1Client) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, NEXServiceV1_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nEXServiceV1Client) KickUser(ctx context.Context, in *KickUserRequest, opts ...grpc.CallOption) (*KickUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KickUserResponse)
	err := c.cc.Invoke(ctx, NEXServiceV1_KickUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nEXServiceV1Client) KickUserAggressive(ctx context.Context, in *KickUserAggressiveRequest, opts ...grpc.CallOption) (*KickUserAggressiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KickUserAggressiveResponse)
	err := c.cc.Invoke(ctx, NEXServiceV1_KickUserAggressive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nEXServiceV1Client) KillUserConnection(ctx context.Context, in *KillUserConnectionRequest, opts ...grpc.CallOption) (*KillUserConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KillUserConnectionResponse)
	err := c.cc.Invoke(ctx, NEXServiceV1_KillUserConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nEXServiceV1Client) GetActiveMatches(ctx context.Context, in *GetActiveMatchesRequest, opts ...grpc.CallOption) (*GetActiveMatchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveMatchesResponse)
	err := c.cc.Invoke(ctx, NEXServiceV1_GetActiveMatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NEXServiceV1Server is the server API for NEXServiceV1 service.
// All implementations must embed UnimplementedNEXServiceV1Server
// for forward compatibility.
type NEXServiceV1Server interface {
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	// Remove a user gracefully using the built in DISCONNECT system
	KickUser(context.Context, *KickUserRequest) (*KickUserResponse, error)
	// Remove a user aggressively using methods like killing the internal RC4 stream along with graceful methods
	KickUserAggressive(context.Context, *KickUserAggressiveRequest) (*KickUserAggressiveResponse, error)
	// Remove a user by any means necessary
	KillUserConnection(context.Context, *KillUserConnectionRequest) (*KillUserConnectionResponse, error)
	// Fetch active matches
	GetActiveMatches(context.Context, *GetActiveMatchesRequest) (*GetActiveMatchesResponse, error)
	mustEmbedUnimplementedNEXServiceV1Server()
}

// UnimplementedNEXServiceV1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNEXServiceV1Server struct{}

func (UnimplementedNEXServiceV1Server) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedNEXServiceV1Server) KickUser(context.Context, *KickUserRequest) (*KickUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KickUser not implemented")
}
func (UnimplementedNEXServiceV1Server) KickUserAggressive(context.Context, *KickUserAggressiveRequest) (*KickUserAggressiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KickUserAggressive not implemented")
}
func (UnimplementedNEXServiceV1Server) KillUserConnection(context.Context, *KillUserConnectionRequest) (*KillUserConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KillUserConnection not implemented")
}
func (UnimplementedNEXServiceV1Server) GetActiveMatches(context.Context, *GetActiveMatchesRequest) (*GetActiveMatchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveMatches not implemented")
}
func (UnimplementedNEXServiceV1Server) mustEmbedUnimplementedNEXServiceV1Server() {}
func (UnimplementedNEXServiceV1Server) testEmbeddedByValue()                      {}

// UnsafeNEXServiceV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NEXServiceV1Server will
// result in compilation errors.
type UnsafeNEXServiceV1Server interface {
	mustEmbedUnimplementedNEXServiceV1Server()
}

func RegisterNEXServiceV1Server(s grpc.ServiceRegistrar, srv NEXServiceV1Server) {
	// If the following call panics, it indicates UnimplementedNEXServiceV1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NEXServiceV1_ServiceDesc, srv)
}

func _NEXServiceV1_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NEXServiceV1Server).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NEXServiceV1_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NEXServiceV1Server).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NEXServiceV1_KickUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NEXServiceV1Server).KickUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NEXServiceV1_KickUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NEXServiceV1Server).KickUser(ctx, req.(*KickUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NEXServiceV1_KickUserAggressive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickUserAggressiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NEXServiceV1Server).KickUserAggressive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NEXServiceV1_KickUserAggressive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NEXServiceV1Server).KickUserAggressive(ctx, req.(*KickUserAggressiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NEXServiceV1_KillUserConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillUserConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NEXServiceV1Server).KillUserConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NEXServiceV1_KillUserConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NEXServiceV1Server).KillUserConnection(ctx, req.(*KillUserConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NEXServiceV1_GetActiveMatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveMatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NEXServiceV1Server).GetActiveMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NEXServiceV1_GetActiveMatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NEXServiceV1Server).GetActiveMatches(ctx, req.(*GetActiveMatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NEXServiceV1_ServiceDesc is the grpc.ServiceDesc for NEXServiceV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NEXServiceV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nex.v1.NEXServiceV1",
	HandlerType: (*NEXServiceV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStats",
			Handler:    _NEXServiceV1_GetStats_Handler,
		},
		{
			MethodName: "KickUser",
			Handler:    _NEXServiceV1_KickUser_Handler,
		},
		{
			MethodName: "KickUserAggressive",
			Handler:    _NEXServiceV1_KickUserAggressive_Handler,
		},
		{
			MethodName: "KillUserConnection",
			Handler:    _NEXServiceV1_KillUserConnection_Handler,
		},
		{
			MethodName: "GetActiveMatches",
			Handler:    _NEXServiceV1_GetActiveMatches_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nex/v1/nex_service.proto",
}
