// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: account/v2/account_service.proto

package accountv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountService_GetUserData_FullMethodName                                = "/account.v2.AccountService/GetUserData"
	AccountService_GetNEXPassword_FullMethodName                             = "/account.v2.AccountService/GetNEXPassword"
	AccountService_GetNEXData_FullMethodName                                 = "/account.v2.AccountService/GetNEXData"
	AccountService_UpdatePNIDPermissions_FullMethodName                      = "/account.v2.AccountService/UpdatePNIDPermissions"
	AccountService_ExchangeTokenForUserData_FullMethodName                   = "/account.v2.AccountService/ExchangeTokenForUserData"
	AccountService_ExchangeOAuthTokenForUserData_FullMethodName              = "/account.v2.AccountService/ExchangeOAuthTokenForUserData"
	AccountService_ExchangeNEXTokenForUserData_FullMethodName                = "/account.v2.AccountService/ExchangeNEXTokenForUserData"
	AccountService_ExchangeIndependentServiceTokenForUserData_FullMethodName = "/account.v2.AccountService/ExchangeIndependentServiceTokenForUserData"
	AccountService_ExchangePasswordResetTokenForUserData_FullMethodName      = "/account.v2.AccountService/ExchangePasswordResetTokenForUserData"
	AccountService_ValidateIndependentServiceToken_FullMethodName            = "/account.v2.AccountService/ValidateIndependentServiceToken"
	AccountService_DeleteAccount_FullMethodName                              = "/account.v2.AccountService/DeleteAccount"
	AccountService_ListDevices_FullMethodName                                = "/account.v2.AccountService/ListDevices"
	AccountService_GetDevice_FullMethodName                                  = "/account.v2.AccountService/GetDevice"
	AccountService_UpdateDevice_FullMethodName                               = "/account.v2.AccountService/UpdateDevice"
	AccountService_ListNEXAccounts_FullMethodName                            = "/account.v2.AccountService/ListNEXAccounts"
	AccountService_GetNEXAccount_FullMethodName                              = "/account.v2.AccountService/GetNEXAccount"
	AccountService_UpdateNEXAccount_FullMethodName                           = "/account.v2.AccountService/UpdateNEXAccount"
	AccountService_ListServers_FullMethodName                                = "/account.v2.AccountService/ListServers"
	AccountService_CreateServer_FullMethodName                               = "/account.v2.AccountService/CreateServer"
	AccountService_GetServer_FullMethodName                                  = "/account.v2.AccountService/GetServer"
	AccountService_UpdateServer_FullMethodName                               = "/account.v2.AccountService/UpdateServer"
	AccountService_DeleteServer_FullMethodName                               = "/account.v2.AccountService/DeleteServer"
	AccountService_ListPNIDs_FullMethodName                                  = "/account.v2.AccountService/ListPNIDs"
	AccountService_GetPNID_FullMethodName                                    = "/account.v2.AccountService/GetPNID"
	AccountService_UpdatePNID_FullMethodName                                 = "/account.v2.AccountService/UpdatePNID"
	AccountService_DeletePNID_FullMethodName                                 = "/account.v2.AccountService/DeletePNID"
	AccountService_ListAuditLogs_FullMethodName                              = "/account.v2.AccountService/ListAuditLogs"
	AccountService_ListAuditLogComments_FullMethodName                       = "/account.v2.AccountService/ListAuditLogComments"
	AccountService_CreateAuditLogComment_FullMethodName                      = "/account.v2.AccountService/CreateAuditLogComment"
	AccountService_ListBans_FullMethodName                                   = "/account.v2.AccountService/ListBans"
	AccountService_IssueBan_FullMethodName                                   = "/account.v2.AccountService/IssueBan"
	AccountService_GetBan_FullMethodName                                     = "/account.v2.AccountService/GetBan"
	AccountService_UpdateBan_FullMethodName                                  = "/account.v2.AccountService/UpdateBan"
	AccountService_PardonBan_FullMethodName                                  = "/account.v2.AccountService/PardonBan"
	AccountService_ListBanComments_FullMethodName                            = "/account.v2.AccountService/ListBanComments"
	AccountService_CreateBanComment_FullMethodName                           = "/account.v2.AccountService/CreateBanComment"
)

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AccountService provides access to account server data.
//
// INTERNAL API: This service is intended for internal backend use by trusted servers only,
// such as the admin panel, game servers, etc. It is not designed for public use.
type AccountServiceClient interface {
	// Deprecated: Do not use.
	// GetUserData retrieves details for a specific PNID account.
	// Deprecated: Use GetPNID instead.
	GetUserData(ctx context.Context, in *GetUserDataRequest, opts ...grpc.CallOption) (*GetUserDataResponse, error)
	// GetNEXPassword retrieves a NEX accounts password. Used only by game servers for Kerberos.
	GetNEXPassword(ctx context.Context, in *GetNEXPasswordRequest, opts ...grpc.CallOption) (*GetNEXPasswordResponse, error)
	// Deprecated: Do not use.
	// GetNEXData retrieves details for a specific NEX account.
	// Deprecated: Use GetNEXAccount instead.
	GetNEXData(ctx context.Context, in *GetNEXDataRequest, opts ...grpc.CallOption) (*GetNEXDataResponse, error)
	// Deprecated: Do not use.
	// UpdatePNIDPermissions updates the permissions for a PNID account.
	// Deprecated: Use UpdatePNID instead.
	UpdatePNIDPermissions(ctx context.Context, in *UpdatePNIDPermissionsRequest, opts ...grpc.CallOption) (*UpdatePNIDPermissionsResponse, error)
	// Deprecated: Do not use.
	// ExchangeTokenForUserData exchanges an authentication token for PNID data.
	// Deprecated: Use the type-specific methods instead.
	ExchangeTokenForUserData(ctx context.Context, in *ExchangeTokenForUserDataRequest, opts ...grpc.CallOption) (*ExchangeTokenForUserDataResponse, error)
	// ExchangeOAuthTokenForUserData exchanges an authentication token for PNID data.
	ExchangeOAuthTokenForUserData(ctx context.Context, in *ExchangeOAuthTokenForUserDataRequest, opts ...grpc.CallOption) (*ExchangeOAuthTokenForUserDataResponse, error)
	// ExchangeNEXTokenForUserData exchanges a NEX token for NEX account data.
	ExchangeNEXTokenForUserData(ctx context.Context, in *ExchangeNEXTokenForUserDataRequest, opts ...grpc.CallOption) (*ExchangeNEXTokenForUserDataResponse, error)
	// ExchangeIndependentServiceTokenForUserData exchanges a service token for user data. PNID data is not returned for NASC tokens.
	ExchangeIndependentServiceTokenForUserData(ctx context.Context, in *ExchangeIndependentServiceTokenForUserDataRequest, opts ...grpc.CallOption) (*ExchangeIndependentServiceTokenForUserDataResponse, error)
	// ExchangePasswordResetTokenForUserData exchanges a password reset token for PNID data.
	ExchangePasswordResetTokenForUserData(ctx context.Context, in *ExchangePasswordResetTokenForUserDataRequest, opts ...grpc.CallOption) (*ExchangePasswordResetTokenForUserDataResponse, error)
	// ValidateIndependentServiceToken validates that a service token data is correct, even on expired tokens.
	ValidateIndependentServiceToken(ctx context.Context, in *ValidateIndependentServiceTokenRequest, opts ...grpc.CallOption) (*ValidateIndependentServiceTokenResponse, error)
	// Deprecated: Do not use.
	// DeleteAccount permanently deletes a PNID account.
	// Deprecated: Use DeletePNID instead.
	DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error)
	// ListDevices returns a paginated list of devices.
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	// GetDevice retrieves details for a specific device.
	GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error)
	// UpdateDevice updates device information.
	UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*UpdateDeviceResponse, error)
	// ListNEXAccounts returns a paginated list of NEX accounts.
	ListNEXAccounts(ctx context.Context, in *ListNEXAccountsRequest, opts ...grpc.CallOption) (*ListNEXAccountsResponse, error)
	// GetNEXAccount retrieves details for a specific NEX account.
	GetNEXAccount(ctx context.Context, in *GetNEXAccountRequest, opts ...grpc.CallOption) (*GetNEXAccountResponse, error)
	// UpdateNEXAccount updates NEX account information.
	UpdateNEXAccount(ctx context.Context, in *UpdateNEXAccountRequest, opts ...grpc.CallOption) (*UpdateNEXAccountResponse, error)
	// ListServers returns a paginated list of server configurations.
	ListServers(ctx context.Context, in *ListServersRequest, opts ...grpc.CallOption) (*ListServersResponse, error)
	// CreateServer creates a new server configuration.
	CreateServer(ctx context.Context, in *CreateServerRequest, opts ...grpc.CallOption) (*CreateServerResponse, error)
	// GetServer retrieves the configuration for a specific server.
	GetServer(ctx context.Context, in *GetServerRequest, opts ...grpc.CallOption) (*GetServerResponse, error)
	// UpdateServer updates a server configuration.
	UpdateServer(ctx context.Context, in *UpdateServerRequest, opts ...grpc.CallOption) (*UpdateServerResponse, error)
	// DeleteServer removes a server configuration.
	DeleteServer(ctx context.Context, in *DeleteServerRequest, opts ...grpc.CallOption) (*DeleteServerResponse, error)
	// ListPNIDs returns a paginated list of PNID accounts.
	ListPNIDs(ctx context.Context, in *ListPNIDsRequest, opts ...grpc.CallOption) (*ListPNIDsResponse, error)
	// GetPNID retrieves details for a specific PNID account.
	GetPNID(ctx context.Context, in *GetPNIDRequest, opts ...grpc.CallOption) (*GetPNIDResponse, error)
	// UpdatePNID updates PNID account information.
	UpdatePNID(ctx context.Context, in *UpdatePNIDRequest, opts ...grpc.CallOption) (*UpdatePNIDResponse, error)
	// DeletePNID permanently deletes a PNID account.
	DeletePNID(ctx context.Context, in *DeletePNIDRequest, opts ...grpc.CallOption) (*DeletePNIDResponse, error)
	// ListAuditLogs returns a paginated list of audit log entries.
	ListAuditLogs(ctx context.Context, in *ListAuditLogsRequest, opts ...grpc.CallOption) (*ListAuditLogsResponse, error)
	// ListAuditLogComments returns comments for a specific audit log entry.
	ListAuditLogComments(ctx context.Context, in *ListAuditLogCommentsRequest, opts ...grpc.CallOption) (*ListAuditLogCommentsResponse, error)
	// CreateAuditLogComment adds a comment to an audit log entry.
	CreateAuditLogComment(ctx context.Context, in *CreateAuditLogCommentRequest, opts ...grpc.CallOption) (*CreateAuditLogCommentResponse, error)
	// ListBans returns a paginated list of bans.
	ListBans(ctx context.Context, in *ListBansRequest, opts ...grpc.CallOption) (*ListBansResponse, error)
	// IssueBan creates a new ban. Can target both users and devices.
	IssueBan(ctx context.Context, in *IssueBanRequest, opts ...grpc.CallOption) (*IssueBanResponse, error)
	// GetBan retrieves details for a specific ban.
	GetBan(ctx context.Context, in *GetBanRequest, opts ...grpc.CallOption) (*GetBanResponse, error)
	// UpdateBan modifies an existing ban.
	UpdateBan(ctx context.Context, in *UpdateBanRequest, opts ...grpc.CallOption) (*UpdateBanResponse, error)
	// PardonBan lifts a ban.
	PardonBan(ctx context.Context, in *PardonBanRequest, opts ...grpc.CallOption) (*PardonBanResponse, error)
	// ListBanComments returns comments for a specific ban.
	ListBanComments(ctx context.Context, in *ListBanCommentsRequest, opts ...grpc.CallOption) (*ListBanCommentsResponse, error)
	// CreateBanComment adds a comment to a ban entry.
	CreateBanComment(ctx context.Context, in *CreateBanCommentRequest, opts ...grpc.CallOption) (*CreateBanCommentResponse, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

// Deprecated: Do not use.
func (c *accountServiceClient) GetUserData(ctx context.Context, in *GetUserDataRequest, opts ...grpc.CallOption) (*GetUserDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserDataResponse)
	err := c.cc.Invoke(ctx, AccountService_GetUserData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetNEXPassword(ctx context.Context, in *GetNEXPasswordRequest, opts ...grpc.CallOption) (*GetNEXPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNEXPasswordResponse)
	err := c.cc.Invoke(ctx, AccountService_GetNEXPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *accountServiceClient) GetNEXData(ctx context.Context, in *GetNEXDataRequest, opts ...grpc.CallOption) (*GetNEXDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNEXDataResponse)
	err := c.cc.Invoke(ctx, AccountService_GetNEXData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *accountServiceClient) UpdatePNIDPermissions(ctx context.Context, in *UpdatePNIDPermissionsRequest, opts ...grpc.CallOption) (*UpdatePNIDPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePNIDPermissionsResponse)
	err := c.cc.Invoke(ctx, AccountService_UpdatePNIDPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *accountServiceClient) ExchangeTokenForUserData(ctx context.Context, in *ExchangeTokenForUserDataRequest, opts ...grpc.CallOption) (*ExchangeTokenForUserDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeTokenForUserDataResponse)
	err := c.cc.Invoke(ctx, AccountService_ExchangeTokenForUserData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ExchangeOAuthTokenForUserData(ctx context.Context, in *ExchangeOAuthTokenForUserDataRequest, opts ...grpc.CallOption) (*ExchangeOAuthTokenForUserDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeOAuthTokenForUserDataResponse)
	err := c.cc.Invoke(ctx, AccountService_ExchangeOAuthTokenForUserData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ExchangeNEXTokenForUserData(ctx context.Context, in *ExchangeNEXTokenForUserDataRequest, opts ...grpc.CallOption) (*ExchangeNEXTokenForUserDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeNEXTokenForUserDataResponse)
	err := c.cc.Invoke(ctx, AccountService_ExchangeNEXTokenForUserData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ExchangeIndependentServiceTokenForUserData(ctx context.Context, in *ExchangeIndependentServiceTokenForUserDataRequest, opts ...grpc.CallOption) (*ExchangeIndependentServiceTokenForUserDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeIndependentServiceTokenForUserDataResponse)
	err := c.cc.Invoke(ctx, AccountService_ExchangeIndependentServiceTokenForUserData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ExchangePasswordResetTokenForUserData(ctx context.Context, in *ExchangePasswordResetTokenForUserDataRequest, opts ...grpc.CallOption) (*ExchangePasswordResetTokenForUserDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangePasswordResetTokenForUserDataResponse)
	err := c.cc.Invoke(ctx, AccountService_ExchangePasswordResetTokenForUserData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ValidateIndependentServiceToken(ctx context.Context, in *ValidateIndependentServiceTokenRequest, opts ...grpc.CallOption) (*ValidateIndependentServiceTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateIndependentServiceTokenResponse)
	err := c.cc.Invoke(ctx, AccountService_ValidateIndependentServiceToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *accountServiceClient) DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAccountResponse)
	err := c.cc.Invoke(ctx, AccountService_DeleteAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, AccountService_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceResponse)
	err := c.cc.Invoke(ctx, AccountService_GetDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*UpdateDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDeviceResponse)
	err := c.cc.Invoke(ctx, AccountService_UpdateDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ListNEXAccounts(ctx context.Context, in *ListNEXAccountsRequest, opts ...grpc.CallOption) (*ListNEXAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNEXAccountsResponse)
	err := c.cc.Invoke(ctx, AccountService_ListNEXAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetNEXAccount(ctx context.Context, in *GetNEXAccountRequest, opts ...grpc.CallOption) (*GetNEXAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNEXAccountResponse)
	err := c.cc.Invoke(ctx, AccountService_GetNEXAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdateNEXAccount(ctx context.Context, in *UpdateNEXAccountRequest, opts ...grpc.CallOption) (*UpdateNEXAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNEXAccountResponse)
	err := c.cc.Invoke(ctx, AccountService_UpdateNEXAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ListServers(ctx context.Context, in *ListServersRequest, opts ...grpc.CallOption) (*ListServersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServersResponse)
	err := c.cc.Invoke(ctx, AccountService_ListServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CreateServer(ctx context.Context, in *CreateServerRequest, opts ...grpc.CallOption) (*CreateServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateServerResponse)
	err := c.cc.Invoke(ctx, AccountService_CreateServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetServer(ctx context.Context, in *GetServerRequest, opts ...grpc.CallOption) (*GetServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerResponse)
	err := c.cc.Invoke(ctx, AccountService_GetServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdateServer(ctx context.Context, in *UpdateServerRequest, opts ...grpc.CallOption) (*UpdateServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateServerResponse)
	err := c.cc.Invoke(ctx, AccountService_UpdateServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) DeleteServer(ctx context.Context, in *DeleteServerRequest, opts ...grpc.CallOption) (*DeleteServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteServerResponse)
	err := c.cc.Invoke(ctx, AccountService_DeleteServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ListPNIDs(ctx context.Context, in *ListPNIDsRequest, opts ...grpc.CallOption) (*ListPNIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPNIDsResponse)
	err := c.cc.Invoke(ctx, AccountService_ListPNIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetPNID(ctx context.Context, in *GetPNIDRequest, opts ...grpc.CallOption) (*GetPNIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPNIDResponse)
	err := c.cc.Invoke(ctx, AccountService_GetPNID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdatePNID(ctx context.Context, in *UpdatePNIDRequest, opts ...grpc.CallOption) (*UpdatePNIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePNIDResponse)
	err := c.cc.Invoke(ctx, AccountService_UpdatePNID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) DeletePNID(ctx context.Context, in *DeletePNIDRequest, opts ...grpc.CallOption) (*DeletePNIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePNIDResponse)
	err := c.cc.Invoke(ctx, AccountService_DeletePNID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ListAuditLogs(ctx context.Context, in *ListAuditLogsRequest, opts ...grpc.CallOption) (*ListAuditLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditLogsResponse)
	err := c.cc.Invoke(ctx, AccountService_ListAuditLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ListAuditLogComments(ctx context.Context, in *ListAuditLogCommentsRequest, opts ...grpc.CallOption) (*ListAuditLogCommentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditLogCommentsResponse)
	err := c.cc.Invoke(ctx, AccountService_ListAuditLogComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CreateAuditLogComment(ctx context.Context, in *CreateAuditLogCommentRequest, opts ...grpc.CallOption) (*CreateAuditLogCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAuditLogCommentResponse)
	err := c.cc.Invoke(ctx, AccountService_CreateAuditLogComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ListBans(ctx context.Context, in *ListBansRequest, opts ...grpc.CallOption) (*ListBansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBansResponse)
	err := c.cc.Invoke(ctx, AccountService_ListBans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) IssueBan(ctx context.Context, in *IssueBanRequest, opts ...grpc.CallOption) (*IssueBanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueBanResponse)
	err := c.cc.Invoke(ctx, AccountService_IssueBan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetBan(ctx context.Context, in *GetBanRequest, opts ...grpc.CallOption) (*GetBanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBanResponse)
	err := c.cc.Invoke(ctx, AccountService_GetBan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdateBan(ctx context.Context, in *UpdateBanRequest, opts ...grpc.CallOption) (*UpdateBanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBanResponse)
	err := c.cc.Invoke(ctx, AccountService_UpdateBan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) PardonBan(ctx context.Context, in *PardonBanRequest, opts ...grpc.CallOption) (*PardonBanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PardonBanResponse)
	err := c.cc.Invoke(ctx, AccountService_PardonBan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ListBanComments(ctx context.Context, in *ListBanCommentsRequest, opts ...grpc.CallOption) (*ListBanCommentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBanCommentsResponse)
	err := c.cc.Invoke(ctx, AccountService_ListBanComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CreateBanComment(ctx context.Context, in *CreateBanCommentRequest, opts ...grpc.CallOption) (*CreateBanCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBanCommentResponse)
	err := c.cc.Invoke(ctx, AccountService_CreateBanComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
// All implementations must embed UnimplementedAccountServiceServer
// for forward compatibility.
//
// AccountService provides access to account server data.
//
// INTERNAL API: This service is intended for internal backend use by trusted servers only,
// such as the admin panel, game servers, etc. It is not designed for public use.
type AccountServiceServer interface {
	// Deprecated: Do not use.
	// GetUserData retrieves details for a specific PNID account.
	// Deprecated: Use GetPNID instead.
	GetUserData(context.Context, *GetUserDataRequest) (*GetUserDataResponse, error)
	// GetNEXPassword retrieves a NEX accounts password. Used only by game servers for Kerberos.
	GetNEXPassword(context.Context, *GetNEXPasswordRequest) (*GetNEXPasswordResponse, error)
	// Deprecated: Do not use.
	// GetNEXData retrieves details for a specific NEX account.
	// Deprecated: Use GetNEXAccount instead.
	GetNEXData(context.Context, *GetNEXDataRequest) (*GetNEXDataResponse, error)
	// Deprecated: Do not use.
	// UpdatePNIDPermissions updates the permissions for a PNID account.
	// Deprecated: Use UpdatePNID instead.
	UpdatePNIDPermissions(context.Context, *UpdatePNIDPermissionsRequest) (*UpdatePNIDPermissionsResponse, error)
	// Deprecated: Do not use.
	// ExchangeTokenForUserData exchanges an authentication token for PNID data.
	// Deprecated: Use the type-specific methods instead.
	ExchangeTokenForUserData(context.Context, *ExchangeTokenForUserDataRequest) (*ExchangeTokenForUserDataResponse, error)
	// ExchangeOAuthTokenForUserData exchanges an authentication token for PNID data.
	ExchangeOAuthTokenForUserData(context.Context, *ExchangeOAuthTokenForUserDataRequest) (*ExchangeOAuthTokenForUserDataResponse, error)
	// ExchangeNEXTokenForUserData exchanges a NEX token for NEX account data.
	ExchangeNEXTokenForUserData(context.Context, *ExchangeNEXTokenForUserDataRequest) (*ExchangeNEXTokenForUserDataResponse, error)
	// ExchangeIndependentServiceTokenForUserData exchanges a service token for user data. PNID data is not returned for NASC tokens.
	ExchangeIndependentServiceTokenForUserData(context.Context, *ExchangeIndependentServiceTokenForUserDataRequest) (*ExchangeIndependentServiceTokenForUserDataResponse, error)
	// ExchangePasswordResetTokenForUserData exchanges a password reset token for PNID data.
	ExchangePasswordResetTokenForUserData(context.Context, *ExchangePasswordResetTokenForUserDataRequest) (*ExchangePasswordResetTokenForUserDataResponse, error)
	// ValidateIndependentServiceToken validates that a service token data is correct, even on expired tokens.
	ValidateIndependentServiceToken(context.Context, *ValidateIndependentServiceTokenRequest) (*ValidateIndependentServiceTokenResponse, error)
	// Deprecated: Do not use.
	// DeleteAccount permanently deletes a PNID account.
	// Deprecated: Use DeletePNID instead.
	DeleteAccount(context.Context, *DeleteAccountRequest) (*DeleteAccountResponse, error)
	// ListDevices returns a paginated list of devices.
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	// GetDevice retrieves details for a specific device.
	GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error)
	// UpdateDevice updates device information.
	UpdateDevice(context.Context, *UpdateDeviceRequest) (*UpdateDeviceResponse, error)
	// ListNEXAccounts returns a paginated list of NEX accounts.
	ListNEXAccounts(context.Context, *ListNEXAccountsRequest) (*ListNEXAccountsResponse, error)
	// GetNEXAccount retrieves details for a specific NEX account.
	GetNEXAccount(context.Context, *GetNEXAccountRequest) (*GetNEXAccountResponse, error)
	// UpdateNEXAccount updates NEX account information.
	UpdateNEXAccount(context.Context, *UpdateNEXAccountRequest) (*UpdateNEXAccountResponse, error)
	// ListServers returns a paginated list of server configurations.
	ListServers(context.Context, *ListServersRequest) (*ListServersResponse, error)
	// CreateServer creates a new server configuration.
	CreateServer(context.Context, *CreateServerRequest) (*CreateServerResponse, error)
	// GetServer retrieves the configuration for a specific server.
	GetServer(context.Context, *GetServerRequest) (*GetServerResponse, error)
	// UpdateServer updates a server configuration.
	UpdateServer(context.Context, *UpdateServerRequest) (*UpdateServerResponse, error)
	// DeleteServer removes a server configuration.
	DeleteServer(context.Context, *DeleteServerRequest) (*DeleteServerResponse, error)
	// ListPNIDs returns a paginated list of PNID accounts.
	ListPNIDs(context.Context, *ListPNIDsRequest) (*ListPNIDsResponse, error)
	// GetPNID retrieves details for a specific PNID account.
	GetPNID(context.Context, *GetPNIDRequest) (*GetPNIDResponse, error)
	// UpdatePNID updates PNID account information.
	UpdatePNID(context.Context, *UpdatePNIDRequest) (*UpdatePNIDResponse, error)
	// DeletePNID permanently deletes a PNID account.
	DeletePNID(context.Context, *DeletePNIDRequest) (*DeletePNIDResponse, error)
	// ListAuditLogs returns a paginated list of audit log entries.
	ListAuditLogs(context.Context, *ListAuditLogsRequest) (*ListAuditLogsResponse, error)
	// ListAuditLogComments returns comments for a specific audit log entry.
	ListAuditLogComments(context.Context, *ListAuditLogCommentsRequest) (*ListAuditLogCommentsResponse, error)
	// CreateAuditLogComment adds a comment to an audit log entry.
	CreateAuditLogComment(context.Context, *CreateAuditLogCommentRequest) (*CreateAuditLogCommentResponse, error)
	// ListBans returns a paginated list of bans.
	ListBans(context.Context, *ListBansRequest) (*ListBansResponse, error)
	// IssueBan creates a new ban. Can target both users and devices.
	IssueBan(context.Context, *IssueBanRequest) (*IssueBanResponse, error)
	// GetBan retrieves details for a specific ban.
	GetBan(context.Context, *GetBanRequest) (*GetBanResponse, error)
	// UpdateBan modifies an existing ban.
	UpdateBan(context.Context, *UpdateBanRequest) (*UpdateBanResponse, error)
	// PardonBan lifts a ban.
	PardonBan(context.Context, *PardonBanRequest) (*PardonBanResponse, error)
	// ListBanComments returns comments for a specific ban.
	ListBanComments(context.Context, *ListBanCommentsRequest) (*ListBanCommentsResponse, error)
	// CreateBanComment adds a comment to a ban entry.
	CreateBanComment(context.Context, *CreateBanCommentRequest) (*CreateBanCommentResponse, error)
	mustEmbedUnimplementedAccountServiceServer()
}

// UnimplementedAccountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountServiceServer struct{}

func (UnimplementedAccountServiceServer) GetUserData(context.Context, *GetUserDataRequest) (*GetUserDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserData not implemented")
}
func (UnimplementedAccountServiceServer) GetNEXPassword(context.Context, *GetNEXPasswordRequest) (*GetNEXPasswordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNEXPassword not implemented")
}
func (UnimplementedAccountServiceServer) GetNEXData(context.Context, *GetNEXDataRequest) (*GetNEXDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNEXData not implemented")
}
func (UnimplementedAccountServiceServer) UpdatePNIDPermissions(context.Context, *UpdatePNIDPermissionsRequest) (*UpdatePNIDPermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePNIDPermissions not implemented")
}
func (UnimplementedAccountServiceServer) ExchangeTokenForUserData(context.Context, *ExchangeTokenForUserDataRequest) (*ExchangeTokenForUserDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeTokenForUserData not implemented")
}
func (UnimplementedAccountServiceServer) ExchangeOAuthTokenForUserData(context.Context, *ExchangeOAuthTokenForUserDataRequest) (*ExchangeOAuthTokenForUserDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeOAuthTokenForUserData not implemented")
}
func (UnimplementedAccountServiceServer) ExchangeNEXTokenForUserData(context.Context, *ExchangeNEXTokenForUserDataRequest) (*ExchangeNEXTokenForUserDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeNEXTokenForUserData not implemented")
}
func (UnimplementedAccountServiceServer) ExchangeIndependentServiceTokenForUserData(context.Context, *ExchangeIndependentServiceTokenForUserDataRequest) (*ExchangeIndependentServiceTokenForUserDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeIndependentServiceTokenForUserData not implemented")
}
func (UnimplementedAccountServiceServer) ExchangePasswordResetTokenForUserData(context.Context, *ExchangePasswordResetTokenForUserDataRequest) (*ExchangePasswordResetTokenForUserDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangePasswordResetTokenForUserData not implemented")
}
func (UnimplementedAccountServiceServer) ValidateIndependentServiceToken(context.Context, *ValidateIndependentServiceTokenRequest) (*ValidateIndependentServiceTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateIndependentServiceToken not implemented")
}
func (UnimplementedAccountServiceServer) DeleteAccount(context.Context, *DeleteAccountRequest) (*DeleteAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAccount not implemented")
}
func (UnimplementedAccountServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedAccountServiceServer) GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDevice not implemented")
}
func (UnimplementedAccountServiceServer) UpdateDevice(context.Context, *UpdateDeviceRequest) (*UpdateDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDevice not implemented")
}
func (UnimplementedAccountServiceServer) ListNEXAccounts(context.Context, *ListNEXAccountsRequest) (*ListNEXAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNEXAccounts not implemented")
}
func (UnimplementedAccountServiceServer) GetNEXAccount(context.Context, *GetNEXAccountRequest) (*GetNEXAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNEXAccount not implemented")
}
func (UnimplementedAccountServiceServer) UpdateNEXAccount(context.Context, *UpdateNEXAccountRequest) (*UpdateNEXAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNEXAccount not implemented")
}
func (UnimplementedAccountServiceServer) ListServers(context.Context, *ListServersRequest) (*ListServersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServers not implemented")
}
func (UnimplementedAccountServiceServer) CreateServer(context.Context, *CreateServerRequest) (*CreateServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateServer not implemented")
}
func (UnimplementedAccountServiceServer) GetServer(context.Context, *GetServerRequest) (*GetServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServer not implemented")
}
func (UnimplementedAccountServiceServer) UpdateServer(context.Context, *UpdateServerRequest) (*UpdateServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateServer not implemented")
}
func (UnimplementedAccountServiceServer) DeleteServer(context.Context, *DeleteServerRequest) (*DeleteServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteServer not implemented")
}
func (UnimplementedAccountServiceServer) ListPNIDs(context.Context, *ListPNIDsRequest) (*ListPNIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPNIDs not implemented")
}
func (UnimplementedAccountServiceServer) GetPNID(context.Context, *GetPNIDRequest) (*GetPNIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPNID not implemented")
}
func (UnimplementedAccountServiceServer) UpdatePNID(context.Context, *UpdatePNIDRequest) (*UpdatePNIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePNID not implemented")
}
func (UnimplementedAccountServiceServer) DeletePNID(context.Context, *DeletePNIDRequest) (*DeletePNIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePNID not implemented")
}
func (UnimplementedAccountServiceServer) ListAuditLogs(context.Context, *ListAuditLogsRequest) (*ListAuditLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAuditLogs not implemented")
}
func (UnimplementedAccountServiceServer) ListAuditLogComments(context.Context, *ListAuditLogCommentsRequest) (*ListAuditLogCommentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAuditLogComments not implemented")
}
func (UnimplementedAccountServiceServer) CreateAuditLogComment(context.Context, *CreateAuditLogCommentRequest) (*CreateAuditLogCommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAuditLogComment not implemented")
}
func (UnimplementedAccountServiceServer) ListBans(context.Context, *ListBansRequest) (*ListBansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBans not implemented")
}
func (UnimplementedAccountServiceServer) IssueBan(context.Context, *IssueBanRequest) (*IssueBanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueBan not implemented")
}
func (UnimplementedAccountServiceServer) GetBan(context.Context, *GetBanRequest) (*GetBanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBan not implemented")
}
func (UnimplementedAccountServiceServer) UpdateBan(context.Context, *UpdateBanRequest) (*UpdateBanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBan not implemented")
}
func (UnimplementedAccountServiceServer) PardonBan(context.Context, *PardonBanRequest) (*PardonBanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PardonBan not implemented")
}
func (UnimplementedAccountServiceServer) ListBanComments(context.Context, *ListBanCommentsRequest) (*ListBanCommentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBanComments not implemented")
}
func (UnimplementedAccountServiceServer) CreateBanComment(context.Context, *CreateBanCommentRequest) (*CreateBanCommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBanComment not implemented")
}
func (UnimplementedAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {}
func (UnimplementedAccountServiceServer) testEmbeddedByValue()                        {}

// UnsafeAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServiceServer will
// result in compilation errors.
type UnsafeAccountServiceServer interface {
	mustEmbedUnimplementedAccountServiceServer()
}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	// If the following call panics, it indicates UnimplementedAccountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountService_ServiceDesc, srv)
}

func _AccountService_GetUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetUserData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetUserData(ctx, req.(*GetUserDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetNEXPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNEXPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetNEXPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetNEXPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetNEXPassword(ctx, req.(*GetNEXPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetNEXData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNEXDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetNEXData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetNEXData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetNEXData(ctx, req.(*GetNEXDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdatePNIDPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePNIDPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdatePNIDPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_UpdatePNIDPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdatePNIDPermissions(ctx, req.(*UpdatePNIDPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ExchangeTokenForUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeTokenForUserDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ExchangeTokenForUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ExchangeTokenForUserData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ExchangeTokenForUserData(ctx, req.(*ExchangeTokenForUserDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ExchangeOAuthTokenForUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeOAuthTokenForUserDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ExchangeOAuthTokenForUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ExchangeOAuthTokenForUserData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ExchangeOAuthTokenForUserData(ctx, req.(*ExchangeOAuthTokenForUserDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ExchangeNEXTokenForUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeNEXTokenForUserDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ExchangeNEXTokenForUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ExchangeNEXTokenForUserData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ExchangeNEXTokenForUserData(ctx, req.(*ExchangeNEXTokenForUserDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ExchangeIndependentServiceTokenForUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeIndependentServiceTokenForUserDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ExchangeIndependentServiceTokenForUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ExchangeIndependentServiceTokenForUserData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ExchangeIndependentServiceTokenForUserData(ctx, req.(*ExchangeIndependentServiceTokenForUserDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ExchangePasswordResetTokenForUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangePasswordResetTokenForUserDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ExchangePasswordResetTokenForUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ExchangePasswordResetTokenForUserData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ExchangePasswordResetTokenForUserData(ctx, req.(*ExchangePasswordResetTokenForUserDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ValidateIndependentServiceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateIndependentServiceTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ValidateIndependentServiceToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ValidateIndependentServiceToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ValidateIndependentServiceToken(ctx, req.(*ValidateIndependentServiceTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_DeleteAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).DeleteAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_DeleteAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).DeleteAccount(ctx, req.(*DeleteAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetDevice(ctx, req.(*GetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_UpdateDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdateDevice(ctx, req.(*UpdateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ListNEXAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNEXAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ListNEXAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ListNEXAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ListNEXAccounts(ctx, req.(*ListNEXAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetNEXAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNEXAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetNEXAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetNEXAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetNEXAccount(ctx, req.(*GetNEXAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdateNEXAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNEXAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdateNEXAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_UpdateNEXAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdateNEXAccount(ctx, req.(*UpdateNEXAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ListServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ListServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ListServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ListServers(ctx, req.(*ListServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CreateServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_CreateServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateServer(ctx, req.(*CreateServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetServer(ctx, req.(*GetServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdateServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdateServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_UpdateServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdateServer(ctx, req.(*UpdateServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_DeleteServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).DeleteServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_DeleteServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).DeleteServer(ctx, req.(*DeleteServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ListPNIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPNIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ListPNIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ListPNIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ListPNIDs(ctx, req.(*ListPNIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetPNID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPNIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetPNID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetPNID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetPNID(ctx, req.(*GetPNIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdatePNID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePNIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdatePNID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_UpdatePNID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdatePNID(ctx, req.(*UpdatePNIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_DeletePNID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePNIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).DeletePNID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_DeletePNID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).DeletePNID(ctx, req.(*DeletePNIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ListAuditLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ListAuditLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ListAuditLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ListAuditLogs(ctx, req.(*ListAuditLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ListAuditLogComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditLogCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ListAuditLogComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ListAuditLogComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ListAuditLogComments(ctx, req.(*ListAuditLogCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CreateAuditLogComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuditLogCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateAuditLogComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_CreateAuditLogComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateAuditLogComment(ctx, req.(*CreateAuditLogCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ListBans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ListBans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ListBans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ListBans(ctx, req.(*ListBansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_IssueBan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueBanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).IssueBan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_IssueBan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).IssueBan(ctx, req.(*IssueBanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetBan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetBan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetBan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetBan(ctx, req.(*GetBanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdateBan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdateBan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_UpdateBan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdateBan(ctx, req.(*UpdateBanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_PardonBan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PardonBanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).PardonBan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_PardonBan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).PardonBan(ctx, req.(*PardonBanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ListBanComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBanCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ListBanComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ListBanComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ListBanComments(ctx, req.(*ListBanCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CreateBanComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBanCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateBanComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_CreateBanComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateBanComment(ctx, req.(*CreateBanCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountService_ServiceDesc is the grpc.ServiceDesc for AccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "account.v2.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserData",
			Handler:    _AccountService_GetUserData_Handler,
		},
		{
			MethodName: "GetNEXPassword",
			Handler:    _AccountService_GetNEXPassword_Handler,
		},
		{
			MethodName: "GetNEXData",
			Handler:    _AccountService_GetNEXData_Handler,
		},
		{
			MethodName: "UpdatePNIDPermissions",
			Handler:    _AccountService_UpdatePNIDPermissions_Handler,
		},
		{
			MethodName: "ExchangeTokenForUserData",
			Handler:    _AccountService_ExchangeTokenForUserData_Handler,
		},
		{
			MethodName: "ExchangeOAuthTokenForUserData",
			Handler:    _AccountService_ExchangeOAuthTokenForUserData_Handler,
		},
		{
			MethodName: "ExchangeNEXTokenForUserData",
			Handler:    _AccountService_ExchangeNEXTokenForUserData_Handler,
		},
		{
			MethodName: "ExchangeIndependentServiceTokenForUserData",
			Handler:    _AccountService_ExchangeIndependentServiceTokenForUserData_Handler,
		},
		{
			MethodName: "ExchangePasswordResetTokenForUserData",
			Handler:    _AccountService_ExchangePasswordResetTokenForUserData_Handler,
		},
		{
			MethodName: "ValidateIndependentServiceToken",
			Handler:    _AccountService_ValidateIndependentServiceToken_Handler,
		},
		{
			MethodName: "DeleteAccount",
			Handler:    _AccountService_DeleteAccount_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _AccountService_ListDevices_Handler,
		},
		{
			MethodName: "GetDevice",
			Handler:    _AccountService_GetDevice_Handler,
		},
		{
			MethodName: "UpdateDevice",
			Handler:    _AccountService_UpdateDevice_Handler,
		},
		{
			MethodName: "ListNEXAccounts",
			Handler:    _AccountService_ListNEXAccounts_Handler,
		},
		{
			MethodName: "GetNEXAccount",
			Handler:    _AccountService_GetNEXAccount_Handler,
		},
		{
			MethodName: "UpdateNEXAccount",
			Handler:    _AccountService_UpdateNEXAccount_Handler,
		},
		{
			MethodName: "ListServers",
			Handler:    _AccountService_ListServers_Handler,
		},
		{
			MethodName: "CreateServer",
			Handler:    _AccountService_CreateServer_Handler,
		},
		{
			MethodName: "GetServer",
			Handler:    _AccountService_GetServer_Handler,
		},
		{
			MethodName: "UpdateServer",
			Handler:    _AccountService_UpdateServer_Handler,
		},
		{
			MethodName: "DeleteServer",
			Handler:    _AccountService_DeleteServer_Handler,
		},
		{
			MethodName: "ListPNIDs",
			Handler:    _AccountService_ListPNIDs_Handler,
		},
		{
			MethodName: "GetPNID",
			Handler:    _AccountService_GetPNID_Handler,
		},
		{
			MethodName: "UpdatePNID",
			Handler:    _AccountService_UpdatePNID_Handler,
		},
		{
			MethodName: "DeletePNID",
			Handler:    _AccountService_DeletePNID_Handler,
		},
		{
			MethodName: "ListAuditLogs",
			Handler:    _AccountService_ListAuditLogs_Handler,
		},
		{
			MethodName: "ListAuditLogComments",
			Handler:    _AccountService_ListAuditLogComments_Handler,
		},
		{
			MethodName: "CreateAuditLogComment",
			Handler:    _AccountService_CreateAuditLogComment_Handler,
		},
		{
			MethodName: "ListBans",
			Handler:    _AccountService_ListBans_Handler,
		},
		{
			MethodName: "IssueBan",
			Handler:    _AccountService_IssueBan_Handler,
		},
		{
			MethodName: "GetBan",
			Handler:    _AccountService_GetBan_Handler,
		},
		{
			MethodName: "UpdateBan",
			Handler:    _AccountService_UpdateBan_Handler,
		},
		{
			MethodName: "PardonBan",
			Handler:    _AccountService_PardonBan_Handler,
		},
		{
			MethodName: "ListBanComments",
			Handler:    _AccountService_ListBanComments_Handler,
		},
		{
			MethodName: "CreateBanComment",
			Handler:    _AccountService_CreateBanComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account/v2/account_service.proto",
}
