// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: account/v2/validate_independent_service_token_rpc.proto

package accountv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateIndependentServiceTokenRequest struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Provider      IndependentServiceTokenProviderType `protobuf:"varint,1,opt,name=provider,proto3,enum=account.v2.IndependentServiceTokenProviderType" json:"provider,omitempty"`
	ClientId      *string                             `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"` // * For NNAS
	TitleIds      []string                            `protobuf:"bytes,3,rep,name=title_ids,json=titleIds,proto3" json:"title_ids,omitempty"`       // * For NASC
	Token         string                              `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateIndependentServiceTokenRequest) Reset() {
	*x = ValidateIndependentServiceTokenRequest{}
	mi := &file_account_v2_validate_independent_service_token_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateIndependentServiceTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateIndependentServiceTokenRequest) ProtoMessage() {}

func (x *ValidateIndependentServiceTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_validate_independent_service_token_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateIndependentServiceTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateIndependentServiceTokenRequest) Descriptor() ([]byte, []int) {
	return file_account_v2_validate_independent_service_token_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateIndependentServiceTokenRequest) GetProvider() IndependentServiceTokenProviderType {
	if x != nil {
		return x.Provider
	}
	return IndependentServiceTokenProviderType_INDEPENDENT_SERVICE_TOKEN_PROVIDER_TYPE_UNSPECIFIED
}

func (x *ValidateIndependentServiceTokenRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *ValidateIndependentServiceTokenRequest) GetTitleIds() []string {
	if x != nil {
		return x.TitleIds
	}
	return nil
}

func (x *ValidateIndependentServiceTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateIndependentServiceTokenResponse struct {
	state         protoimpl.MessageState                            `protogen:"open.v1"`
	IsValid       bool                                              `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	UserInfo      *ValidateIndependentServiceTokenResponse_UserInfo `protobuf:"bytes,2,opt,name=user_info,json=userInfo,proto3,oneof" json:"user_info,omitempty"` // * Not present if is_valid is false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateIndependentServiceTokenResponse) Reset() {
	*x = ValidateIndependentServiceTokenResponse{}
	mi := &file_account_v2_validate_independent_service_token_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateIndependentServiceTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateIndependentServiceTokenResponse) ProtoMessage() {}

func (x *ValidateIndependentServiceTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_validate_independent_service_token_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateIndependentServiceTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateIndependentServiceTokenResponse) Descriptor() ([]byte, []int) {
	return file_account_v2_validate_independent_service_token_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateIndependentServiceTokenResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateIndependentServiceTokenResponse) GetUserInfo() *ValidateIndependentServiceTokenResponse_UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type ValidateIndependentServiceTokenResponse_UserInfo struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	AccessBetaServers      bool                   `protobuf:"varint,1,opt,name=access_beta_servers,json=accessBetaServers,proto3" json:"access_beta_servers,omitempty"`
	AccessDeveloperServers bool                   `protobuf:"varint,2,opt,name=access_developer_servers,json=accessDeveloperServers,proto3" json:"access_developer_servers,omitempty"`
	Ban                    *Ban                   `protobuf:"bytes,3,opt,name=ban,proto3,oneof" json:"ban,omitempty"` // * Not present if not banned
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ValidateIndependentServiceTokenResponse_UserInfo) Reset() {
	*x = ValidateIndependentServiceTokenResponse_UserInfo{}
	mi := &file_account_v2_validate_independent_service_token_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateIndependentServiceTokenResponse_UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateIndependentServiceTokenResponse_UserInfo) ProtoMessage() {}

func (x *ValidateIndependentServiceTokenResponse_UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_validate_independent_service_token_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateIndependentServiceTokenResponse_UserInfo.ProtoReflect.Descriptor instead.
func (*ValidateIndependentServiceTokenResponse_UserInfo) Descriptor() ([]byte, []int) {
	return file_account_v2_validate_independent_service_token_rpc_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ValidateIndependentServiceTokenResponse_UserInfo) GetAccessBetaServers() bool {
	if x != nil {
		return x.AccessBetaServers
	}
	return false
}

func (x *ValidateIndependentServiceTokenResponse_UserInfo) GetAccessDeveloperServers() bool {
	if x != nil {
		return x.AccessDeveloperServers
	}
	return false
}

func (x *ValidateIndependentServiceTokenResponse_UserInfo) GetBan() *Ban {
	if x != nil {
		return x.Ban
	}
	return nil
}

var File_account_v2_validate_independent_service_token_rpc_proto protoreflect.FileDescriptor

const file_account_v2_validate_independent_service_token_rpc_proto_rawDesc = "" +
	"\n" +
	"7account/v2/validate_independent_service_token_rpc.proto\x12\n" +
	"account.v2\x1a\x1caccount/v2/ban_details.proto\x1aEaccount/v2/exchange_independent_service_token_for_user_data_rpc.proto\"\xd8\x01\n" +
	"&ValidateIndependentServiceTokenRequest\x12K\n" +
	"\bprovider\x18\x01 \x01(\x0e2/.account.v2.IndependentServiceTokenProviderTypeR\bprovider\x12 \n" +
	"\tclient_id\x18\x02 \x01(\tH\x00R\bclientId\x88\x01\x01\x12\x1b\n" +
	"\ttitle_ids\x18\x03 \x03(\tR\btitleIds\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05tokenB\f\n" +
	"\n" +
	"_client_id\"\xd9\x02\n" +
	"'ValidateIndependentServiceTokenResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12^\n" +
	"\tuser_info\x18\x02 \x01(\v2<.account.v2.ValidateIndependentServiceTokenResponse.UserInfoH\x00R\buserInfo\x88\x01\x01\x1a\xa4\x01\n" +
	"\bUserInfo\x12.\n" +
	"\x13access_beta_servers\x18\x01 \x01(\bR\x11accessBetaServers\x128\n" +
	"\x18access_developer_servers\x18\x02 \x01(\bR\x16accessDeveloperServers\x12&\n" +
	"\x03ban\x18\x03 \x01(\v2\x0f.account.v2.BanH\x00R\x03ban\x88\x01\x01B\x06\n" +
	"\x04_banB\f\n" +
	"\n" +
	"_user_infoB\xbb\x01\n" +
	"\x0ecom.account.v2B'ValidateIndependentServiceTokenRpcProtoP\x01Z7github.com/PretendoNetwork/grpc/go/account/v2;accountv2\xa2\x02\x03AXX\xaa\x02\n" +
	"Account.V2\xca\x02\n" +
	"Account\\V2\xe2\x02\x16Account\\V2\\GPBMetadata\xea\x02\vAccount::V2b\x06proto3"

var (
	file_account_v2_validate_independent_service_token_rpc_proto_rawDescOnce sync.Once
	file_account_v2_validate_independent_service_token_rpc_proto_rawDescData []byte
)

func file_account_v2_validate_independent_service_token_rpc_proto_rawDescGZIP() []byte {
	file_account_v2_validate_independent_service_token_rpc_proto_rawDescOnce.Do(func() {
		file_account_v2_validate_independent_service_token_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v2_validate_independent_service_token_rpc_proto_rawDesc), len(file_account_v2_validate_independent_service_token_rpc_proto_rawDesc)))
	})
	return file_account_v2_validate_independent_service_token_rpc_proto_rawDescData
}

var file_account_v2_validate_independent_service_token_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_account_v2_validate_independent_service_token_rpc_proto_goTypes = []any{
	(*ValidateIndependentServiceTokenRequest)(nil),           // 0: account.v2.ValidateIndependentServiceTokenRequest
	(*ValidateIndependentServiceTokenResponse)(nil),          // 1: account.v2.ValidateIndependentServiceTokenResponse
	(*ValidateIndependentServiceTokenResponse_UserInfo)(nil), // 2: account.v2.ValidateIndependentServiceTokenResponse.UserInfo
	(IndependentServiceTokenProviderType)(0),                 // 3: account.v2.IndependentServiceTokenProviderType
	(*Ban)(nil),                                              // 4: account.v2.Ban
}
var file_account_v2_validate_independent_service_token_rpc_proto_depIdxs = []int32{
	3, // 0: account.v2.ValidateIndependentServiceTokenRequest.provider:type_name -> account.v2.IndependentServiceTokenProviderType
	2, // 1: account.v2.ValidateIndependentServiceTokenResponse.user_info:type_name -> account.v2.ValidateIndependentServiceTokenResponse.UserInfo
	4, // 2: account.v2.ValidateIndependentServiceTokenResponse.UserInfo.ban:type_name -> account.v2.Ban
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_account_v2_validate_independent_service_token_rpc_proto_init() }
func file_account_v2_validate_independent_service_token_rpc_proto_init() {
	if File_account_v2_validate_independent_service_token_rpc_proto != nil {
		return
	}
	file_account_v2_ban_details_proto_init()
	file_account_v2_exchange_independent_service_token_for_user_data_rpc_proto_init()
	file_account_v2_validate_independent_service_token_rpc_proto_msgTypes[0].OneofWrappers = []any{}
	file_account_v2_validate_independent_service_token_rpc_proto_msgTypes[1].OneofWrappers = []any{}
	file_account_v2_validate_independent_service_token_rpc_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v2_validate_independent_service_token_rpc_proto_rawDesc), len(file_account_v2_validate_independent_service_token_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_v2_validate_independent_service_token_rpc_proto_goTypes,
		DependencyIndexes: file_account_v2_validate_independent_service_token_rpc_proto_depIdxs,
		MessageInfos:      file_account_v2_validate_independent_service_token_rpc_proto_msgTypes,
	}.Build()
	File_account_v2_validate_independent_service_token_rpc_proto = out.File
	file_account_v2_validate_independent_service_token_rpc_proto_goTypes = nil
	file_account_v2_validate_independent_service_token_rpc_proto_depIdxs = nil
}
