/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter eslint_disable,output_javascript,output_legacy_commonjs,ts_nocheck
// @generated from protobuf file "friends/v2/friends_service.proto" (package "friends.v2", syntax proto3)
// tslint:disable
// @ts-nocheck
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FriendsService = void 0;
/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter eslint_disable,output_javascript,output_legacy_commonjs,ts_nocheck
// @generated from protobuf file "friends/v2/friends_service.proto" (package "friends.v2", syntax proto3)
// tslint:disable
// @ts-nocheck
const deny_friend_request_rpc_1 = require("./deny_friend_request_rpc");
const deny_friend_request_rpc_2 = require("./deny_friend_request_rpc");
const accept_friend_request_rpc_1 = require("./accept_friend_request_rpc");
const accept_friend_request_rpc_2 = require("./accept_friend_request_rpc");
const get_user_friend_requests_incoming_rpc_1 = require("./get_user_friend_requests_incoming_rpc");
const get_user_friend_requests_incoming_rpc_2 = require("./get_user_friend_requests_incoming_rpc");
const send_user_friend_request_rpc_1 = require("./send_user_friend_request_rpc");
const send_user_friend_request_rpc_2 = require("./send_user_friend_request_rpc");
const get_user_friend_pids_rpc_1 = require("./get_user_friend_pids_rpc");
const get_user_friend_pids_rpc_2 = require("./get_user_friend_pids_rpc");
const send_user_notification_wiiu_rpc_1 = require("./send_user_notification_wiiu_rpc");
const send_user_notification_wiiu_rpc_2 = require("./send_user_notification_wiiu_rpc");
const runtime_rpc_1 = require("@protobuf-ts/runtime-rpc");
/**
 * @generated ServiceType for protobuf service friends.v2.FriendsService
 */
exports.FriendsService = new runtime_rpc_1.ServiceType("friends.v2.FriendsService", [
    { name: "SendUserNotificationWiiU", options: {}, I: send_user_notification_wiiu_rpc_2.SendUserNotificationWiiURequest, O: send_user_notification_wiiu_rpc_1.SendUserNotificationWiiUResponse },
    { name: "GetUserFriendPIDs", options: {}, I: get_user_friend_pids_rpc_2.GetUserFriendPIDsRequest, O: get_user_friend_pids_rpc_1.GetUserFriendPIDsResponse },
    { name: "SendUserFriendRequest", options: {}, I: send_user_friend_request_rpc_2.SendUserFriendRequestRequest, O: send_user_friend_request_rpc_1.SendUserFriendRequestResponse },
    { name: "GetUserFriendRequestsIncoming", options: {}, I: get_user_friend_requests_incoming_rpc_2.GetUserFriendRequestsIncomingRequest, O: get_user_friend_requests_incoming_rpc_1.GetUserFriendRequestsIncomingResponse },
    { name: "AcceptFriendRequest", options: {}, I: accept_friend_request_rpc_2.AcceptFriendRequestRequest, O: accept_friend_request_rpc_1.AcceptFriendRequestResponse },
    { name: "DenyFriendRequest", options: {}, I: deny_friend_request_rpc_2.DenyFriendRequestRequest, O: deny_friend_request_rpc_1.DenyFriendRequestResponse }
]);
