"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: friends/v2/get_user_data_wiiu_rpc.proto
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetUserDataWiiUResponse = exports.GetUserDataWiiURequest = exports.protobufPackage = void 0;
/* eslint-disable */
const wire_1 = require("@bufbuild/protobuf/wire");
const friend_info_1 = require("./friend_info");
exports.protobufPackage = "friends.v2";
function createBaseGetUserDataWiiURequest() {
    return { pid: 0 };
}
exports.GetUserDataWiiURequest = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.pid !== 0) {
            writer.uint32(8).uint32(message.pid);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGetUserDataWiiURequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.pid = reader.uint32();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { pid: isSet(object.pid) ? globalThis.Number(object.pid) : 0 };
    },
    toJSON(message) {
        const obj = {};
        if (message.pid !== 0) {
            obj.pid = Math.round(message.pid);
        }
        return obj;
    },
    create(base) {
        return exports.GetUserDataWiiURequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseGetUserDataWiiURequest();
        message.pid = object.pid ?? 0;
        return message;
    },
};
function createBaseGetUserDataWiiUResponse() {
    return { user: undefined };
}
exports.GetUserDataWiiUResponse = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.user !== undefined) {
            friend_info_1.FriendInfoWiiU.encode(message.user, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGetUserDataWiiUResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.user = friend_info_1.FriendInfoWiiU.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { user: isSet(object.user) ? friend_info_1.FriendInfoWiiU.fromJSON(object.user) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.user !== undefined) {
            obj.user = friend_info_1.FriendInfoWiiU.toJSON(message.user);
        }
        return obj;
    },
    create(base) {
        return exports.GetUserDataWiiUResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseGetUserDataWiiUResponse();
        message.user = (object.user !== undefined && object.user !== null)
            ? friend_info_1.FriendInfoWiiU.fromPartial(object.user)
            : undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
