/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter eslint_disable,output_javascript,output_legacy_commonjs,ts_nocheck
// @generated from protobuf file "miiverse/miiverse_service.proto" (package "miiverse", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import type { SMMRequestPostIDResponse } from "./smm_request_post_id_rpc";
import type { SMMRequestPostIDRequest } from "./smm_request_post_id_rpc";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service miiverse.Miiverse
 */
export interface IMiiverseClient {
    /**
     * Used by Super Mario Maker
     *
     * @generated from protobuf rpc: SMMRequestPostId(miiverse.SMMRequestPostIDRequest) returns (miiverse.SMMRequestPostIDResponse);
     */
    sMMRequestPostId(input: SMMRequestPostIDRequest, options?: RpcOptions): UnaryCall<SMMRequestPostIDRequest, SMMRequestPostIDResponse>;
}
/**
 * @generated from protobuf service miiverse.Miiverse
 */
export declare class MiiverseClient implements IMiiverseClient, ServiceInfo {
    private readonly _transport;
    typeName: any;
    methods: any;
    options: any;
    constructor(_transport: RpcTransport);
    /**
     * Used by Super Mario Maker
     *
     * @generated from protobuf rpc: SMMRequestPostId(miiverse.SMMRequestPostIDRequest) returns (miiverse.SMMRequestPostIDResponse);
     */
    sMMRequestPostId(input: SMMRequestPostIDRequest, options?: RpcOptions): UnaryCall<SMMRequestPostIDRequest, SMMRequestPostIDResponse>;
}
