"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: miiverse/miiverse_service.proto
Object.defineProperty(exports, "__esModule", { value: true });
exports.MiiverseDefinition = exports.protobufPackage = void 0;
const smm_request_post_id_rpc_1 = require("./smm_request_post_id_rpc");
exports.protobufPackage = "miiverse";
exports.MiiverseDefinition = {
    name: "Miiverse",
    fullName: "miiverse.Miiverse",
    methods: {
        /** Used by Super Mario Maker */
        sMMRequestPostId: {
            name: "SMMRequestPostId",
            requestType: smm_request_post_id_rpc_1.SMMRequestPostIDRequest,
            requestStream: false,
            responseType: smm_request_post_id_rpc_1.SMMRequestPostIDResponse,
            responseStream: false,
            options: {},
        },
    },
};
