// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: account/v2/get_server_rpc.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Server } from "./server";

export const protobufPackage = "account.v2";

export interface GetServerRequest {
  id: string;
}

export interface GetServerResponse {
  server: Server | undefined;
}

function createBaseGetServerRequest(): GetServerRequest {
  return { id: "" };
}

export const GetServerRequest: MessageFns<GetServerRequest> = {
  encode(message: GetServerRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetServerRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetServerRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetServerRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: GetServerRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create(base?: DeepPartial<GetServerRequest>): GetServerRequest {
    return GetServerRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetServerRequest>): GetServerRequest {
    const message = createBaseGetServerRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseGetServerResponse(): GetServerResponse {
  return { server: undefined };
}

export const GetServerResponse: MessageFns<GetServerResponse> = {
  encode(message: GetServerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.server !== undefined) {
      Server.encode(message.server, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetServerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetServerResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.server = Server.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetServerResponse {
    return { server: isSet(object.server) ? Server.fromJSON(object.server) : undefined };
  },

  toJSON(message: GetServerResponse): unknown {
    const obj: any = {};
    if (message.server !== undefined) {
      obj.server = Server.toJSON(message.server);
    }
    return obj;
  },

  create(base?: DeepPartial<GetServerResponse>): GetServerResponse {
    return GetServerResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetServerResponse>): GetServerResponse {
    const message = createBaseGetServerResponse();
    message.server = (object.server !== undefined && object.server !== null)
      ? Server.fromPartial(object.server)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
