// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: account/v2/list_servers_rpc.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { PageInput, PageResults } from "./page";
import { Server } from "./server";

export const protobufPackage = "account.v2";

export interface ListServersRequest {
  page: PageInput | undefined;
  filter: ListServersRequest_Filter | undefined;
}

export interface ListServersRequest_Filter {
  serviceName?: string | undefined;
  extraJson?: string | undefined;
}

export interface ListServersResponse {
  page: PageResults | undefined;
  items: Server[];
}

function createBaseListServersRequest(): ListServersRequest {
  return { page: undefined, filter: undefined };
}

export const ListServersRequest: MessageFns<ListServersRequest> = {
  encode(message: ListServersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.page !== undefined) {
      PageInput.encode(message.page, writer.uint32(10).fork()).join();
    }
    if (message.filter !== undefined) {
      ListServersRequest_Filter.encode(message.filter, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListServersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListServersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.page = PageInput.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.filter = ListServersRequest_Filter.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListServersRequest {
    return {
      page: isSet(object.page) ? PageInput.fromJSON(object.page) : undefined,
      filter: isSet(object.filter) ? ListServersRequest_Filter.fromJSON(object.filter) : undefined,
    };
  },

  toJSON(message: ListServersRequest): unknown {
    const obj: any = {};
    if (message.page !== undefined) {
      obj.page = PageInput.toJSON(message.page);
    }
    if (message.filter !== undefined) {
      obj.filter = ListServersRequest_Filter.toJSON(message.filter);
    }
    return obj;
  },

  create(base?: DeepPartial<ListServersRequest>): ListServersRequest {
    return ListServersRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListServersRequest>): ListServersRequest {
    const message = createBaseListServersRequest();
    message.page = (object.page !== undefined && object.page !== null) ? PageInput.fromPartial(object.page) : undefined;
    message.filter = (object.filter !== undefined && object.filter !== null)
      ? ListServersRequest_Filter.fromPartial(object.filter)
      : undefined;
    return message;
  },
};

function createBaseListServersRequest_Filter(): ListServersRequest_Filter {
  return { serviceName: undefined, extraJson: undefined };
}

export const ListServersRequest_Filter: MessageFns<ListServersRequest_Filter> = {
  encode(message: ListServersRequest_Filter, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serviceName !== undefined) {
      writer.uint32(10).string(message.serviceName);
    }
    if (message.extraJson !== undefined) {
      writer.uint32(18).string(message.extraJson);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListServersRequest_Filter {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListServersRequest_Filter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serviceName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.extraJson = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListServersRequest_Filter {
    return {
      serviceName: isSet(object.serviceName) ? globalThis.String(object.serviceName) : undefined,
      extraJson: isSet(object.extraJson) ? globalThis.String(object.extraJson) : undefined,
    };
  },

  toJSON(message: ListServersRequest_Filter): unknown {
    const obj: any = {};
    if (message.serviceName !== undefined) {
      obj.serviceName = message.serviceName;
    }
    if (message.extraJson !== undefined) {
      obj.extraJson = message.extraJson;
    }
    return obj;
  },

  create(base?: DeepPartial<ListServersRequest_Filter>): ListServersRequest_Filter {
    return ListServersRequest_Filter.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListServersRequest_Filter>): ListServersRequest_Filter {
    const message = createBaseListServersRequest_Filter();
    message.serviceName = object.serviceName ?? undefined;
    message.extraJson = object.extraJson ?? undefined;
    return message;
  },
};

function createBaseListServersResponse(): ListServersResponse {
  return { page: undefined, items: [] };
}

export const ListServersResponse: MessageFns<ListServersResponse> = {
  encode(message: ListServersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.page !== undefined) {
      PageResults.encode(message.page, writer.uint32(10).fork()).join();
    }
    for (const v of message.items) {
      Server.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListServersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListServersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.page = PageResults.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.items.push(Server.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListServersResponse {
    return {
      page: isSet(object.page) ? PageResults.fromJSON(object.page) : undefined,
      items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => Server.fromJSON(e)) : [],
    };
  },

  toJSON(message: ListServersResponse): unknown {
    const obj: any = {};
    if (message.page !== undefined) {
      obj.page = PageResults.toJSON(message.page);
    }
    if (message.items?.length) {
      obj.items = message.items.map((e) => Server.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<ListServersResponse>): ListServersResponse {
    return ListServersResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListServersResponse>): ListServersResponse {
    const message = createBaseListServersResponse();
    message.page = (object.page !== undefined && object.page !== null)
      ? PageResults.fromPartial(object.page)
      : undefined;
    message.items = object.items?.map((e) => Server.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
