// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: account/v2/list_pnids_rpc.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { GetUserDataResponse } from "./get_user_data_rpc";
import { PageInput, PageResults } from "./page";

export const protobufPackage = "account.v2";

export interface ListPNIDsRequest {
  page: PageInput | undefined;
  filter: ListPNIDsRequest_Filter | undefined;
}

export interface ListPNIDsRequest_Filter {
  pid?: number | undefined;
  friendCode?: string | undefined;
  extraJson?: string | undefined;
}

export interface ListPNIDsResponse {
  page: PageResults | undefined;
  items: GetUserDataResponse[];
}

function createBaseListPNIDsRequest(): ListPNIDsRequest {
  return { page: undefined, filter: undefined };
}

export const ListPNIDsRequest: MessageFns<ListPNIDsRequest> = {
  encode(message: ListPNIDsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.page !== undefined) {
      PageInput.encode(message.page, writer.uint32(10).fork()).join();
    }
    if (message.filter !== undefined) {
      ListPNIDsRequest_Filter.encode(message.filter, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListPNIDsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListPNIDsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.page = PageInput.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.filter = ListPNIDsRequest_Filter.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListPNIDsRequest {
    return {
      page: isSet(object.page) ? PageInput.fromJSON(object.page) : undefined,
      filter: isSet(object.filter) ? ListPNIDsRequest_Filter.fromJSON(object.filter) : undefined,
    };
  },

  toJSON(message: ListPNIDsRequest): unknown {
    const obj: any = {};
    if (message.page !== undefined) {
      obj.page = PageInput.toJSON(message.page);
    }
    if (message.filter !== undefined) {
      obj.filter = ListPNIDsRequest_Filter.toJSON(message.filter);
    }
    return obj;
  },

  create(base?: DeepPartial<ListPNIDsRequest>): ListPNIDsRequest {
    return ListPNIDsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListPNIDsRequest>): ListPNIDsRequest {
    const message = createBaseListPNIDsRequest();
    message.page = (object.page !== undefined && object.page !== null) ? PageInput.fromPartial(object.page) : undefined;
    message.filter = (object.filter !== undefined && object.filter !== null)
      ? ListPNIDsRequest_Filter.fromPartial(object.filter)
      : undefined;
    return message;
  },
};

function createBaseListPNIDsRequest_Filter(): ListPNIDsRequest_Filter {
  return { pid: undefined, friendCode: undefined, extraJson: undefined };
}

export const ListPNIDsRequest_Filter: MessageFns<ListPNIDsRequest_Filter> = {
  encode(message: ListPNIDsRequest_Filter, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pid !== undefined) {
      writer.uint32(8).uint32(message.pid);
    }
    if (message.friendCode !== undefined) {
      writer.uint32(18).string(message.friendCode);
    }
    if (message.extraJson !== undefined) {
      writer.uint32(26).string(message.extraJson);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListPNIDsRequest_Filter {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListPNIDsRequest_Filter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.pid = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.friendCode = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.extraJson = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListPNIDsRequest_Filter {
    return {
      pid: isSet(object.pid) ? globalThis.Number(object.pid) : undefined,
      friendCode: isSet(object.friendCode) ? globalThis.String(object.friendCode) : undefined,
      extraJson: isSet(object.extraJson) ? globalThis.String(object.extraJson) : undefined,
    };
  },

  toJSON(message: ListPNIDsRequest_Filter): unknown {
    const obj: any = {};
    if (message.pid !== undefined) {
      obj.pid = Math.round(message.pid);
    }
    if (message.friendCode !== undefined) {
      obj.friendCode = message.friendCode;
    }
    if (message.extraJson !== undefined) {
      obj.extraJson = message.extraJson;
    }
    return obj;
  },

  create(base?: DeepPartial<ListPNIDsRequest_Filter>): ListPNIDsRequest_Filter {
    return ListPNIDsRequest_Filter.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListPNIDsRequest_Filter>): ListPNIDsRequest_Filter {
    const message = createBaseListPNIDsRequest_Filter();
    message.pid = object.pid ?? undefined;
    message.friendCode = object.friendCode ?? undefined;
    message.extraJson = object.extraJson ?? undefined;
    return message;
  },
};

function createBaseListPNIDsResponse(): ListPNIDsResponse {
  return { page: undefined, items: [] };
}

export const ListPNIDsResponse: MessageFns<ListPNIDsResponse> = {
  encode(message: ListPNIDsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.page !== undefined) {
      PageResults.encode(message.page, writer.uint32(10).fork()).join();
    }
    for (const v of message.items) {
      GetUserDataResponse.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListPNIDsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListPNIDsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.page = PageResults.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.items.push(GetUserDataResponse.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListPNIDsResponse {
    return {
      page: isSet(object.page) ? PageResults.fromJSON(object.page) : undefined,
      items: globalThis.Array.isArray(object?.items)
        ? object.items.map((e: any) => GetUserDataResponse.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListPNIDsResponse): unknown {
    const obj: any = {};
    if (message.page !== undefined) {
      obj.page = PageResults.toJSON(message.page);
    }
    if (message.items?.length) {
      obj.items = message.items.map((e) => GetUserDataResponse.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<ListPNIDsResponse>): ListPNIDsResponse {
    return ListPNIDsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListPNIDsResponse>): ListPNIDsResponse {
    const message = createBaseListPNIDsResponse();
    message.page = (object.page !== undefined && object.page !== null)
      ? PageResults.fromPartial(object.page)
      : undefined;
    message.items = object.items?.map((e) => GetUserDataResponse.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
