// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: account/v2/validate_independent_service_token_rpc.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { BasicUserInfo } from "./basic_user_info";

export const protobufPackage = "account.v2";

export interface ValidateIndependentServiceTokenRequest {
  clientIds: string[];
  token: string;
}

export interface ValidateIndependentServiceTokenResponse {
  isValid: boolean;
  /** Not present if is_valid is false */
  basicUserInfo?: BasicUserInfo | undefined;
}

function createBaseValidateIndependentServiceTokenRequest(): ValidateIndependentServiceTokenRequest {
  return { clientIds: [], token: "" };
}

export const ValidateIndependentServiceTokenRequest: MessageFns<ValidateIndependentServiceTokenRequest> = {
  encode(message: ValidateIndependentServiceTokenRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.clientIds) {
      writer.uint32(10).string(v!);
    }
    if (message.token !== "") {
      writer.uint32(18).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateIndependentServiceTokenRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateIndependentServiceTokenRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientIds.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidateIndependentServiceTokenRequest {
    return {
      clientIds: globalThis.Array.isArray(object?.clientIds)
        ? object.clientIds.map((e: any) => globalThis.String(e))
        : [],
      token: isSet(object.token) ? globalThis.String(object.token) : "",
    };
  },

  toJSON(message: ValidateIndependentServiceTokenRequest): unknown {
    const obj: any = {};
    if (message.clientIds?.length) {
      obj.clientIds = message.clientIds;
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create(base?: DeepPartial<ValidateIndependentServiceTokenRequest>): ValidateIndependentServiceTokenRequest {
    return ValidateIndependentServiceTokenRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ValidateIndependentServiceTokenRequest>): ValidateIndependentServiceTokenRequest {
    const message = createBaseValidateIndependentServiceTokenRequest();
    message.clientIds = object.clientIds?.map((e) => e) || [];
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseValidateIndependentServiceTokenResponse(): ValidateIndependentServiceTokenResponse {
  return { isValid: false, basicUserInfo: undefined };
}

export const ValidateIndependentServiceTokenResponse: MessageFns<ValidateIndependentServiceTokenResponse> = {
  encode(message: ValidateIndependentServiceTokenResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.isValid !== false) {
      writer.uint32(8).bool(message.isValid);
    }
    if (message.basicUserInfo !== undefined) {
      BasicUserInfo.encode(message.basicUserInfo, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateIndependentServiceTokenResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateIndependentServiceTokenResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.isValid = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.basicUserInfo = BasicUserInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidateIndependentServiceTokenResponse {
    return {
      isValid: isSet(object.isValid) ? globalThis.Boolean(object.isValid) : false,
      basicUserInfo: isSet(object.basicUserInfo) ? BasicUserInfo.fromJSON(object.basicUserInfo) : undefined,
    };
  },

  toJSON(message: ValidateIndependentServiceTokenResponse): unknown {
    const obj: any = {};
    if (message.isValid !== false) {
      obj.isValid = message.isValid;
    }
    if (message.basicUserInfo !== undefined) {
      obj.basicUserInfo = BasicUserInfo.toJSON(message.basicUserInfo);
    }
    return obj;
  },

  create(base?: DeepPartial<ValidateIndependentServiceTokenResponse>): ValidateIndependentServiceTokenResponse {
    return ValidateIndependentServiceTokenResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ValidateIndependentServiceTokenResponse>): ValidateIndependentServiceTokenResponse {
    const message = createBaseValidateIndependentServiceTokenResponse();
    message.isValid = object.isValid ?? false;
    message.basicUserInfo = (object.basicUserInfo !== undefined && object.basicUserInfo !== null)
      ? BasicUserInfo.fromPartial(object.basicUserInfo)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
