syntax = "proto3";

package miiverse.v2;

enum PostType {
  text = 0;
  memo = 1;
  screenshot = 2;
}

enum QueryType {
  followings = 0;
  self = 1;
}

enum SortBy {
  new = 0;
  popular = 1;
}

message PostPainting {
  string format = 1;
  string content = 2;
  uint32 size = 3;
  string url = 4;
};

message PostScreenshot {
  uint32 size = 1;
  string url = 2;
};

message PostTopicTag {
  string name = 1;
  string title_id = 2;
};

message PostData {
  optional string app_data = 1;
  optional string body = 2;
  string community_id = 3;
  uint32 country_id = 4;
  string created_at = 5;
  uint32 feeling_id = 6;
  string id = 7;
  uint32 is_autopost = 8;
  uint32 is_community_private_autopost = 9;
  uint32 is_spoiler = 10;
  uint32 is_app_jumpable = 11;
  uint32 empathy_count = 12;
  uint32 language_id = 13;
  optional string mii = 14;
  optional string mii_face_url = 15;
  uint32 number = 16;
  optional PostPainting painting = 17;
  uint32 pid = 18;
  uint32 platform_id = 19;
  uint32 region_id = 20;
  uint32 reply_count = 21;
  string screen_name = 22;
  optional PostScreenshot screenshot = 23;
  optional PostTopicTag topic_tag = 24;
  string title_id = 25;
};
