// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: friends/v2/get_user_data_3ds_rpc.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { FriendInfo3DS } from "./friend_info";

export const protobufPackage = "friends.v2";

export interface GetUserData3DSRequest {
  pid: number;
}

export interface GetUserData3DSResponse {
  user: FriendInfo3DS | undefined;
}

function createBaseGetUserData3DSRequest(): GetUserData3DSRequest {
  return { pid: 0 };
}

export const GetUserData3DSRequest: MessageFns<GetUserData3DSRequest> = {
  encode(message: GetUserData3DSRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pid !== 0) {
      writer.uint32(8).uint32(message.pid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserData3DSRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserData3DSRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.pid = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUserData3DSRequest {
    return { pid: isSet(object.pid) ? globalThis.Number(object.pid) : 0 };
  },

  toJSON(message: GetUserData3DSRequest): unknown {
    const obj: any = {};
    if (message.pid !== 0) {
      obj.pid = Math.round(message.pid);
    }
    return obj;
  },

  create(base?: DeepPartial<GetUserData3DSRequest>): GetUserData3DSRequest {
    return GetUserData3DSRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetUserData3DSRequest>): GetUserData3DSRequest {
    const message = createBaseGetUserData3DSRequest();
    message.pid = object.pid ?? 0;
    return message;
  },
};

function createBaseGetUserData3DSResponse(): GetUserData3DSResponse {
  return { user: undefined };
}

export const GetUserData3DSResponse: MessageFns<GetUserData3DSResponse> = {
  encode(message: GetUserData3DSResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== undefined) {
      FriendInfo3DS.encode(message.user, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserData3DSResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserData3DSResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user = FriendInfo3DS.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUserData3DSResponse {
    return { user: isSet(object.user) ? FriendInfo3DS.fromJSON(object.user) : undefined };
  },

  toJSON(message: GetUserData3DSResponse): unknown {
    const obj: any = {};
    if (message.user !== undefined) {
      obj.user = FriendInfo3DS.toJSON(message.user);
    }
    return obj;
  },

  create(base?: DeepPartial<GetUserData3DSResponse>): GetUserData3DSResponse {
    return GetUserData3DSResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetUserData3DSResponse>): GetUserData3DSResponse {
    const message = createBaseGetUserData3DSResponse();
    message.user = (object.user !== undefined && object.user !== null)
      ? FriendInfo3DS.fromPartial(object.user)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
