"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: nex/nex_service.proto
Object.defineProperty(exports, "__esModule", { value: true });
exports.NEXDefinition = exports.protobufPackage = void 0;
const empty_1 = require("../google/protobuf/empty");
const get_active_matches_1 = require("./get_active_matches");
exports.protobufPackage = "nex";
exports.NEXDefinition = {
    name: "NEX",
    fullName: "nex.NEX",
    methods: {
        getActiveMatches: {
            name: "GetActiveMatches",
            requestType: empty_1.Empty,
            requestStream: false,
            responseType: get_active_matches_1.ActiveMatchesResponse,
            responseStream: false,
            options: {},
        },
    },
};
