// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: nex/nex_service.proto

/* eslint-disable */
import { type CallContext, type CallOptions } from "nice-grpc-common";
import { Empty } from "../google/protobuf/empty";
import { ActiveMatchesResponse } from "./get_active_matches";

export const protobufPackage = "nex";

export type NEXDefinition = typeof NEXDefinition;
export const NEXDefinition = {
  name: "NEX",
  fullName: "nex.NEX",
  methods: {
    getActiveMatches: {
      name: "GetActiveMatches",
      requestType: Empty,
      requestStream: false,
      responseType: ActiveMatchesResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface NEXServiceImplementation<CallContextExt = {}> {
  getActiveMatches(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<ActiveMatchesResponse>>;
}

export interface NEXClient<CallOptionsExt = {}> {
  getActiveMatches(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<ActiveMatchesResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;
