/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter eslint_disable,output_javascript,output_legacy_commonjs,ts_nocheck
// @generated from protobuf file "boss/v2/boss_service.proto" (package "boss.v2", syntax proto3)
// tslint:disable
// @ts-nocheck
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BossServiceClient = void 0;
const boss_service_1 = require("./boss_service");
const runtime_rpc_1 = require("@protobuf-ts/runtime-rpc");
/**
 * @generated from protobuf service boss.v2.BossService
 */
class BossServiceClient {
    constructor(_transport) {
        this._transport = _transport;
        this.typeName = boss_service_1.BossService.typeName;
        this.methods = boss_service_1.BossService.methods;
        this.options = boss_service_1.BossService.options;
    }
    /**
     * @generated from protobuf rpc: ListKnownBOSSApps(boss.v2.ListKnownBOSSAppsRequest) returns (boss.v2.ListKnownBOSSAppsResponse);
     */
    listKnownBOSSApps(input, options) {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return runtime_rpc_1.stackIntercept("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListTasks(boss.v2.ListTasksRequest) returns (boss.v2.ListTasksResponse);
     */
    listTasks(input, options) {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return runtime_rpc_1.stackIntercept("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RegisterTask(boss.v2.RegisterTaskRequest) returns (boss.v2.RegisterTaskResponse);
     */
    registerTask(input, options) {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return runtime_rpc_1.stackIntercept("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateTask(boss.v2.UpdateTaskRequest) returns (boss.v2.UpdateTaskResponse);
     */
    updateTask(input, options) {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return runtime_rpc_1.stackIntercept("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteTask(boss.v2.DeleteTaskRequest) returns (boss.v2.DeleteTaskResponse);
     */
    deleteTask(input, options) {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return runtime_rpc_1.stackIntercept("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListFiles(boss.v2.ListFilesRequest) returns (boss.v2.ListFilesResponse);
     */
    listFiles(input, options) {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return runtime_rpc_1.stackIntercept("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UploadFile(boss.v2.UploadFileRequest) returns (boss.v2.UploadFileResponse);
     */
    uploadFile(input, options) {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return runtime_rpc_1.stackIntercept("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateFileMetadata(boss.v2.UpdateFileMetadataRequest) returns (boss.v2.UpdateFileMetadataResponse);
     */
    updateFileMetadata(input, options) {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return runtime_rpc_1.stackIntercept("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteFile(boss.v2.DeleteFileRequest) returns (boss.v2.DeleteFileResponse);
     */
    deleteFile(input, options) {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return runtime_rpc_1.stackIntercept("unary", this._transport, method, opt, input);
    }
}
exports.BossServiceClient = BossServiceClient;
