// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: boss/v2/list_files_ctr.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { FileCTR } from "./file_ctr";

export const protobufPackage = "boss.v2";

export interface ListFilesCTRRequest {
  taskId: string;
  bossAppId: string;
  country?: string | undefined;
  language?: string | undefined;
}

export interface ListFilesCTRResponse {
  files: FileCTR[];
}

function createBaseListFilesCTRRequest(): ListFilesCTRRequest {
  return { taskId: "", bossAppId: "", country: undefined, language: undefined };
}

export const ListFilesCTRRequest: MessageFns<ListFilesCTRRequest> = {
  encode(message: ListFilesCTRRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.taskId !== "") {
      writer.uint32(10).string(message.taskId);
    }
    if (message.bossAppId !== "") {
      writer.uint32(18).string(message.bossAppId);
    }
    if (message.country !== undefined) {
      writer.uint32(26).string(message.country);
    }
    if (message.language !== undefined) {
      writer.uint32(34).string(message.language);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListFilesCTRRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListFilesCTRRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.taskId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.bossAppId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.country = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.language = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListFilesCTRRequest {
    return {
      taskId: isSet(object.taskId) ? globalThis.String(object.taskId) : "",
      bossAppId: isSet(object.bossAppId) ? globalThis.String(object.bossAppId) : "",
      country: isSet(object.country) ? globalThis.String(object.country) : undefined,
      language: isSet(object.language) ? globalThis.String(object.language) : undefined,
    };
  },

  toJSON(message: ListFilesCTRRequest): unknown {
    const obj: any = {};
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    if (message.bossAppId !== "") {
      obj.bossAppId = message.bossAppId;
    }
    if (message.country !== undefined) {
      obj.country = message.country;
    }
    if (message.language !== undefined) {
      obj.language = message.language;
    }
    return obj;
  },

  create(base?: DeepPartial<ListFilesCTRRequest>): ListFilesCTRRequest {
    return ListFilesCTRRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListFilesCTRRequest>): ListFilesCTRRequest {
    const message = createBaseListFilesCTRRequest();
    message.taskId = object.taskId ?? "";
    message.bossAppId = object.bossAppId ?? "";
    message.country = object.country ?? undefined;
    message.language = object.language ?? undefined;
    return message;
  },
};

function createBaseListFilesCTRResponse(): ListFilesCTRResponse {
  return { files: [] };
}

export const ListFilesCTRResponse: MessageFns<ListFilesCTRResponse> = {
  encode(message: ListFilesCTRResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.files) {
      FileCTR.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListFilesCTRResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListFilesCTRResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.files.push(FileCTR.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListFilesCTRResponse {
    return { files: globalThis.Array.isArray(object?.files) ? object.files.map((e: any) => FileCTR.fromJSON(e)) : [] };
  },

  toJSON(message: ListFilesCTRResponse): unknown {
    const obj: any = {};
    if (message.files?.length) {
      obj.files = message.files.map((e) => FileCTR.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<ListFilesCTRResponse>): ListFilesCTRResponse {
    return ListFilesCTRResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListFilesCTRResponse>): ListFilesCTRResponse {
    const message = createBaseListFilesCTRResponse();
    message.files = object.files?.map((e) => FileCTR.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
