"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: boss/v2/payload_content_ctr.proto
Object.defineProperty(exports, "__esModule", { value: true });
exports.PayloadContentCTR = exports.protobufPackage = void 0;
/* eslint-disable */
const wire_1 = require("@bufbuild/protobuf/wire");
exports.protobufPackage = "boss.v2";
function createBasePayloadContentCTR() {
    return { titleId: 0n, contentDatatype: 0, nsDataId: 0, version: 0, content: Buffer.alloc(0) };
}
exports.PayloadContentCTR = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.titleId !== 0n) {
            if (BigInt.asUintN(64, message.titleId) !== message.titleId) {
                throw new globalThis.Error("value provided for field message.titleId of type uint64 too large");
            }
            writer.uint32(8).uint64(message.titleId);
        }
        if (message.contentDatatype !== 0) {
            writer.uint32(16).uint32(message.contentDatatype);
        }
        if (message.nsDataId !== 0) {
            writer.uint32(24).uint32(message.nsDataId);
        }
        if (message.version !== 0) {
            writer.uint32(32).uint32(message.version);
        }
        if (message.content.length !== 0) {
            writer.uint32(42).bytes(message.content);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBasePayloadContentCTR();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.titleId = reader.uint64();
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.contentDatatype = reader.uint32();
                    continue;
                }
                case 3: {
                    if (tag !== 24) {
                        break;
                    }
                    message.nsDataId = reader.uint32();
                    continue;
                }
                case 4: {
                    if (tag !== 32) {
                        break;
                    }
                    message.version = reader.uint32();
                    continue;
                }
                case 5: {
                    if (tag !== 42) {
                        break;
                    }
                    message.content = Buffer.from(reader.bytes());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            titleId: isSet(object.titleId) ? BigInt(object.titleId) : 0n,
            contentDatatype: isSet(object.contentDatatype) ? globalThis.Number(object.contentDatatype) : 0,
            nsDataId: isSet(object.nsDataId) ? globalThis.Number(object.nsDataId) : 0,
            version: isSet(object.version) ? globalThis.Number(object.version) : 0,
            content: isSet(object.content) ? Buffer.from(bytesFromBase64(object.content)) : Buffer.alloc(0),
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.titleId !== 0n) {
            obj.titleId = message.titleId.toString();
        }
        if (message.contentDatatype !== 0) {
            obj.contentDatatype = Math.round(message.contentDatatype);
        }
        if (message.nsDataId !== 0) {
            obj.nsDataId = Math.round(message.nsDataId);
        }
        if (message.version !== 0) {
            obj.version = Math.round(message.version);
        }
        if (message.content.length !== 0) {
            obj.content = base64FromBytes(message.content);
        }
        return obj;
    },
    create(base) {
        return exports.PayloadContentCTR.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBasePayloadContentCTR();
        message.titleId = object.titleId ?? 0n;
        message.contentDatatype = object.contentDatatype ?? 0;
        message.nsDataId = object.nsDataId ?? 0;
        message.version = object.version ?? 0;
        message.content = object.content ?? Buffer.alloc(0);
        return message;
    },
};
function bytesFromBase64(b64) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
}
function base64FromBytes(arr) {
    return globalThis.Buffer.from(arr).toString("base64");
}
function isSet(value) {
    return value !== null && value !== undefined;
}
