"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: nex/v1/nex_service.proto
Object.defineProperty(exports, "__esModule", { value: true });
exports.NEXServiceV1Definition = exports.protobufPackage = void 0;
const get_stats_rpc_1 = require("./get_stats_rpc");
const kick_user_aggressive_rpc_1 = require("./kick_user_aggressive_rpc");
const kick_user_rpc_1 = require("./kick_user_rpc");
const kill_user_connection_rpc_1 = require("./kill_user_connection_rpc");
exports.protobufPackage = "nex.v1";
exports.NEXServiceV1Definition = {
    name: "NEXServiceV1",
    fullName: "nex.v1.NEXServiceV1",
    methods: {
        getStats: {
            name: "GetStats",
            requestType: get_stats_rpc_1.GetStatsRequest,
            requestStream: false,
            responseType: get_stats_rpc_1.GetStatsResponse,
            responseStream: false,
            options: {},
        },
        /** Remove a user gracefully using the built in DISCONNECT system */
        kickUser: {
            name: "KickUser",
            requestType: kick_user_rpc_1.KickUserRequest,
            requestStream: false,
            responseType: kick_user_rpc_1.KickUserResponse,
            responseStream: false,
            options: {},
        },
        /** Remove a user aggressively using methods like killing the internal RC4 stream along with graceful methods */
        kickUserAggressive: {
            name: "KickUserAggressive",
            requestType: kick_user_aggressive_rpc_1.KickUserAggressiveRequest,
            requestStream: false,
            responseType: kick_user_aggressive_rpc_1.KickUserAggressiveResponse,
            responseStream: false,
            options: {},
        },
        /** Remove a user by any means necessary */
        killUserConnection: {
            name: "KillUserConnection",
            requestType: kill_user_connection_rpc_1.KillUserConnectionRequest,
            requestStream: false,
            responseType: kill_user_connection_rpc_1.KillUserConnectionResponse,
            responseStream: false,
            options: {},
        },
    },
};
